//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/tools/AeSimpleSHA1.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqLibToolsAeSimpleSHA1_H_
#define _ComFqLibToolsAeSimpleSHA1_H_

@class IOSByteArray;

#import "JreEmulation.h"

@interface ComFqLibToolsAeSimpleSHA1 : NSObject {
}

+ (NSString *)convertToHexWithByteArray:(IOSByteArray *)data;

+ (NSString *)SHA1WithNSString:(NSString *)text;

+ (NSString *)repeat20TimesWithNSString:(NSString *)text;

+ (NSString *)repeat20TimesAndSHA1WithNSString:(NSString *)text;

- (id)init;

@end

__attribute__((always_inline)) inline void ComFqLibToolsAeSimpleSHA1_init() {}

#endif // _ComFqLibToolsAeSimpleSHA1_H_
