//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/AlarmClock.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/AlarmClock.java"

#include "AlarmClock.h"
#include "JSONObject.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"

@implementation ComFqHalcyonEntityAlarmClock


#line 28
- (JavaUtilArrayList *)getTimerList {
  
#line 29
  return timerList_;
}


#line 32
- (JavaUtilHashMap *)getmTimeHashMap {
  
#line 33
  return mTimeHashMap_;
}


#line 36
- (void)setmTimeHashMapWithJavaUtilHashMap:(JavaUtilHashMap *)mTimeHashMap {
  
#line 37
  self->mTimeHashMap_ = mTimeHashMap;
}

- (void)setTimerListWithJavaUtilArrayList:(JavaUtilArrayList *)timerList {
  
#line 43
  self->timerList_ = timerList;
}


#line 46
- (NSString *)getTimerContent {
  
#line 47
  return timerContent_;
}


#line 50
- (void)setTimerContentWithNSString:(NSString *)timerContent {
  
#line 51
  self->timerContent_ = timerContent;
}


#line 54
- (int)getUserId {
  
#line 55
  return userId_;
}


#line 58
- (void)setUserIdWithInt:(int)userId {
  
#line 59
  self->userId_ = userId;
}


#line 62
- (int)getTimerId {
  
#line 63
  return timerId_;
}


#line 66
- (void)setTimerIdWithInt:(int)timerId {
  
#line 67
  self->timerId_ = timerId;
}


#line 70
- (long long int)getTimerDate {
  
#line 71
  return timerDate_;
}


#line 74
- (void)setTimerDateWithLong:(long long int)timerDate {
  
#line 75
  self->timerDate_ = timerDate;
}


#line 79
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  self->timerId_ = [((FQJSONObject *) nil_chk(json)) optIntWithNSString:@"id"];
  self->userId_ = [json optIntWithNSString:@"userId"];
  self->timerDate_ = [json optIntWithNSString:@"timer_date"];
  self->timerContent_ = [json optStringWithNSString:@"timer_content"];
  [super setAtttributeByjsonWithFQJSONObject:json];
}


#line 88
- (void)test {
}

- (id)init {
  return [super init];
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityAlarmClock *)other {
  [super copyAllFieldsTo:other];
  other->mTimeHashMap_ = mTimeHashMap_;
  other->timerContent_ = timerContent_;
  other->timerDate_ = timerDate_;
  other->timerId_ = timerId_;
  other->timerList_ = timerList_;
  other->userId_ = userId_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getTimerList", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "getmTimeHashMap", NULL, "Ljava.util.HashMap;", 0x1, NULL },
    { "setmTimeHashMapWithJavaUtilHashMap:", "setmTimeHashMap", "V", 0x1, NULL },
    { "setTimerListWithJavaUtilArrayList:", "setTimerList", "V", 0x1, NULL },
    { "getTimerContent", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setTimerContentWithNSString:", "setTimerContent", "V", 0x1, NULL },
    { "getUserId", NULL, "I", 0x1, NULL },
    { "setUserIdWithInt:", "setUserId", "V", 0x1, NULL },
    { "getTimerId", NULL, "I", 0x1, NULL },
    { "setTimerIdWithInt:", "setTimerId", "V", 0x1, NULL },
    { "getTimerDate", NULL, "J", 0x1, NULL },
    { "setTimerDateWithLong:", "setTimerDate", "V", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "test", NULL, "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "timerContent_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "userId_", NULL, 0x2, "I", NULL,  },
    { "timerId_", NULL, 0x2, "I", NULL,  },
    { "timerDate_", NULL, 0x2, "J", NULL,  },
    { "mTimeHashMap_", NULL, 0x2, "Ljava.util.HashMap;", NULL,  },
    { "timerList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityAlarmClock = { "AlarmClock", "com.fq.halcyon.entity", NULL, 0x1, 15, methods, 6, fields, 0, NULL};
  return &_ComFqHalcyonEntityAlarmClock;
}

@end
