//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/api/ApiSystem.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonApiApiSystem_H_
#define _ComFqHalcyonApiApiSystem_H_

@class ComFqHalcyonApiApiSystem_API_TYPEEnum;
@class ComFqHalcyonEntityPhoto;
@class ComFqHalcyonEntityPhotoRecord;
@class ComFqHttpAsyncFQHttpParams;
@class FQJSONObject;
@class HalcyonHttpResponseHandle;
@class IOSByteArray;
@class IOSObjectArray;
@class JavaIoFile;
@class JavaLangThrowable;
@class JavaUtilArrayList;
@class JavaUtilHashMap;
@protocol ComFqHalcyonApiApiSystem_NotifyOk;
@protocol ComFqHttpPotocolHttpRequestPotocol;
@protocol ComFqLibCallbackICallback;

#import "JreEmulation.h"
#include "FQBinaryResponseHandle.h"
#include "FQHttpResponseHandle.h"
#include "FQJsonResponseHandle.h"
#include "java/lang/Enum.h"

@interface ComFqHalcyonApiApiSystem : NSObject {
 @public
  JavaUtilArrayList *handles_;
  id<ComFqHalcyonApiApiSystem_NotifyOk> mNotify_;
  JavaUtilHashMap *mCurrnetDownUrls_;
}

- (void)setNotifyWithComFqHalcyonApiApiSystem_NotifyOk:(id<ComFqHalcyonApiApiSystem_NotifyOk>)mNotify;

- (void)onDataSet;

+ (ComFqHalcyonApiApiSystem *)getInstance;

- (id)init;

- (id<ComFqHttpPotocolHttpRequestPotocol>)requireWithNSString:(NSString *)url
                    withComFqHalcyonApiApiSystem_API_TYPEEnum:(ComFqHalcyonApiApiSystem_API_TYPEEnum *)type
                                withHalcyonHttpResponseHandle:(HalcyonHttpResponseHandle *)handle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)requireWithNSString:(NSString *)url
                               withComFqHttpAsyncFQHttpParams:(ComFqHttpAsyncFQHttpParams *)params
                    withComFqHalcyonApiApiSystem_API_TYPEEnum:(ComFqHalcyonApiApiSystem_API_TYPEEnum *)type
                                withHalcyonHttpResponseHandle:(HalcyonHttpResponseHandle *)handle;

- (void)getImageWithComFqHalcyonEntityPhoto:(ComFqHalcyonEntityPhoto *)photo
              withComFqLibCallbackICallback:(id<ComFqLibCallbackICallback>)callback
                                withBoolean:(BOOL)thumbnail;

- (void)getHeadImageWithComFqHalcyonEntityPhoto:(ComFqHalcyonEntityPhoto *)photo
                  withComFqLibCallbackICallback:(id<ComFqLibCallbackICallback>)callback
                                    withBoolean:(BOOL)thumbnail
                                        withInt:(int)Type;

- (void)getImageWithComFqHalcyonEntityPhotoRecord:(ComFqHalcyonEntityPhotoRecord *)image
                    withComFqLibCallbackICallback:(id<ComFqLibCallbackICallback>)callback
                                      withBoolean:(BOOL)thumbnail;

- (void)getImageWithComFqHalcyonEntityPhotoRecord:(ComFqHalcyonEntityPhotoRecord *)image
                    withComFqLibCallbackICallback:(id<ComFqLibCallbackICallback>)callback;

- (void)getImageWithComFqHalcyonEntityPhoto:(ComFqHalcyonEntityPhoto *)photo
              withComFqLibCallbackICallback:(id<ComFqLibCallbackICallback>)callback;

- (FQBinaryResponseHandle *)getImgaeHandelWithJavaIoFile:(JavaIoFile *)localFile
                                            withNSString:(NSString *)url;

- (void)onErrorWithNSString:(NSString *)url
withComFqHttpAsyncFQHttpParams:(ComFqHttpAsyncFQHttpParams *)params
withComFqHalcyonApiApiSystem_API_TYPEEnum:(ComFqHalcyonApiApiSystem_API_TYPEEnum *)type
withHalcyonHttpResponseHandle:(HalcyonHttpResponseHandle *)handle
                    withInt:(int)code
               withNSString:(NSString *)msg
      withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)onSuccessWithNSString:(NSString *)url
withComFqHttpAsyncFQHttpParams:(ComFqHttpAsyncFQHttpParams *)params
withComFqHalcyonApiApiSystem_API_TYPEEnum:(ComFqHalcyonApiApiSystem_API_TYPEEnum *)type
withHalcyonHttpResponseHandle:(HalcyonHttpResponseHandle *)handle
             withFQJSONObject:(FQJSONObject *)result;

- (void)copyAllFieldsTo:(ComFqHalcyonApiApiSystem *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonApiApiSystem_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem, handles_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem, mNotify_, id<ComFqHalcyonApiApiSystem_NotifyOk>)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem, mCurrnetDownUrls_, JavaUtilHashMap *)

FOUNDATION_EXPORT ComFqHalcyonApiApiSystem *ComFqHalcyonApiApiSystem_instance_;
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonApiApiSystem, instance_, ComFqHalcyonApiApiSystem *)
J2OBJC_STATIC_FIELD_SETTER(ComFqHalcyonApiApiSystem, instance_, ComFqHalcyonApiApiSystem *)

typedef enum {
  ComFqHalcyonApiApiSystem_API_TYPE_BROW = 0,
  ComFqHalcyonApiApiSystem_API_TYPE_OFFLINE = 1,
  ComFqHalcyonApiApiSystem_API_TYPE_ONLINE = 2,
  ComFqHalcyonApiApiSystem_API_TYPE_DIRECT = 3,
} ComFqHalcyonApiApiSystem_API_TYPE;

@interface ComFqHalcyonApiApiSystem_API_TYPEEnum : JavaLangEnum < NSCopying > {
}
+ (IOSObjectArray *)values;
+ (ComFqHalcyonApiApiSystem_API_TYPEEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

FOUNDATION_EXPORT BOOL ComFqHalcyonApiApiSystem_API_TYPEEnum_initialized;
J2OBJC_STATIC_INIT(ComFqHalcyonApiApiSystem_API_TYPEEnum)

FOUNDATION_EXPORT ComFqHalcyonApiApiSystem_API_TYPEEnum *ComFqHalcyonApiApiSystem_API_TYPEEnum_values[];

#define ComFqHalcyonApiApiSystem_API_TYPEEnum_BROW ComFqHalcyonApiApiSystem_API_TYPEEnum_values[ComFqHalcyonApiApiSystem_API_TYPE_BROW]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonApiApiSystem_API_TYPEEnum, BROW, ComFqHalcyonApiApiSystem_API_TYPEEnum *)

#define ComFqHalcyonApiApiSystem_API_TYPEEnum_OFFLINE ComFqHalcyonApiApiSystem_API_TYPEEnum_values[ComFqHalcyonApiApiSystem_API_TYPE_OFFLINE]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonApiApiSystem_API_TYPEEnum, OFFLINE, ComFqHalcyonApiApiSystem_API_TYPEEnum *)

#define ComFqHalcyonApiApiSystem_API_TYPEEnum_ONLINE ComFqHalcyonApiApiSystem_API_TYPEEnum_values[ComFqHalcyonApiApiSystem_API_TYPE_ONLINE]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonApiApiSystem_API_TYPEEnum, ONLINE, ComFqHalcyonApiApiSystem_API_TYPEEnum *)

#define ComFqHalcyonApiApiSystem_API_TYPEEnum_DIRECT ComFqHalcyonApiApiSystem_API_TYPEEnum_values[ComFqHalcyonApiApiSystem_API_TYPE_DIRECT]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonApiApiSystem_API_TYPEEnum, DIRECT, ComFqHalcyonApiApiSystem_API_TYPEEnum *)

@protocol ComFqHalcyonApiApiSystem_NotifyOk < NSObject, JavaObject >

- (void)onImageSeted;

@end

__attribute__((always_inline)) inline void ComFqHalcyonApiApiSystem_NotifyOk_init() {}

@interface ComFqHalcyonApiApiSystem_$1 : FQJsonResponseHandle {
 @public
  ComFqHalcyonApiApiSystem *this$0_;
  NSString *val$url_;
  ComFqHttpAsyncFQHttpParams *val$params_;
  ComFqHalcyonApiApiSystem_API_TYPEEnum *val$type_;
  HalcyonHttpResponseHandle *val$handle_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleJsonWithFQJSONObject:(FQJSONObject *)json;

- (id)initWithComFqHalcyonApiApiSystem:(ComFqHalcyonApiApiSystem *)outer$
                          withNSString:(NSString *)capture$0
        withComFqHttpAsyncFQHttpParams:(ComFqHttpAsyncFQHttpParams *)capture$1
withComFqHalcyonApiApiSystem_API_TYPEEnum:(ComFqHalcyonApiApiSystem_API_TYPEEnum *)capture$2
         withHalcyonHttpResponseHandle:(HalcyonHttpResponseHandle *)capture$3;

@end

__attribute__((always_inline)) inline void ComFqHalcyonApiApiSystem_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$1, this$0_, ComFqHalcyonApiApiSystem *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$1, val$url_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$1, val$params_, ComFqHttpAsyncFQHttpParams *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$1, val$type_, ComFqHalcyonApiApiSystem_API_TYPEEnum *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$1, val$handle_, HalcyonHttpResponseHandle *)

@interface ComFqHalcyonApiApiSystem_$2 : FQBinaryResponseHandle {
 @public
  ComFqHalcyonApiApiSystem *this$0_;
  NSString *val$url_;
  JavaIoFile *val$localFile_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleBinaryDataWithByteArray:(IOSByteArray *)data;

- (IOSObjectArray *)getRequestHeaders;

- (void)setRequestHeadersWithComFqHttpAsyncFQHeaderArray:(IOSObjectArray *)headers;

- (id)initWithComFqHalcyonApiApiSystem:(ComFqHalcyonApiApiSystem *)outer$
                          withNSString:(NSString *)capture$0
                        withJavaIoFile:(JavaIoFile *)capture$1;

@end

__attribute__((always_inline)) inline void ComFqHalcyonApiApiSystem_$2_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$2, this$0_, ComFqHalcyonApiApiSystem *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$2, val$url_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$2, val$localFile_, JavaIoFile *)

@interface ComFqHalcyonApiApiSystem_$2_$1 : NSObject < FQHttpResponseHandle > {
 @public
  ComFqHalcyonApiApiSystem_$2 *this$0_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleResponseWithByteArray:(IOSByteArray *)data;

- (IOSObjectArray *)getRequestHeaders;

- (void)setRequestHeadersWithComFqHttpAsyncFQHeaderArray:(IOSObjectArray *)headers;

- (id)initWithComFqHalcyonApiApiSystem_$2:(ComFqHalcyonApiApiSystem_$2 *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonApiApiSystem_$2_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonApiApiSystem_$2_$1, this$0_, ComFqHalcyonApiApiSystem_$2 *)

#endif // _ComFqHalcyonApiApiSystem_H_
