//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/ChangeDPNameLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2ChangeDPNameLogic_H_
#define _ComFqHalcyonLogic2ChangeDPNameLogic_H_

@class JavaLangThrowable;
@protocol ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback;

#import "JreEmulation.h"
#include "FQHttpResponseInterface.h"
#include "HalcyonHttpResponseHandle.h"

@interface ComFqHalcyonLogic2ChangeDPNameLogic : NSObject {
}

- (void)changeDPNameWithNSString:(NSString *)name
withComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback:(id<ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback>)callback;

- (id)init;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2ChangeDPNameLogic_init() {}

@protocol ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback < ComFqHttpPotocolFQHttpResponseInterface, NSObject, JavaObject >
- (void)feedChangeDPNameWithBoolean:(BOOL)isSuccess
                       withNSString:(NSString *)msg;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback_init() {}

@interface ComFqHalcyonLogic2ChangeDPNameLogic_$1 : HalcyonHttpResponseHandle {
 @public
  id<ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback> val$callback_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback:(id<ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback>)capture$0;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2ChangeDPNameLogic_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2ChangeDPNameLogic_$1, val$callback_, id<ComFqHalcyonLogic2ChangeDPNameLogic_ChangeDPNameCallback>)

#endif // _ComFqHalcyonLogic2ChangeDPNameLogic_H_
