//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic/CheckVersionLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic/CheckVersionLogic.java"

#include "ApiSystem.h"
#include "CheckVersionLogic.h"
#include "FQHttpParams.h"
#include "HttpRequestPotocol.h"
#include "IOSClass.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "UriConstants.h"
#include "Version.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/HashMap.h"


#line 14
@implementation ComFqHalcyonLogicCheckVersionLogic


#line 25
- (void)checkVersionWithInt:(int)type
withComFqHalcyonLogicCheckVersionLogic_VersionCallback:(id<ComFqHalcyonLogicCheckVersionLogic_VersionCallback>)callback {
  
#line 26
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"client_type" withId:[JavaLangInteger valueOfWithInt:type]];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  NSString *url = [NSString stringWithFormat:@"%@/users/check_client_version.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  
#line 32
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:[[ComFqHalcyonLogicCheckVersionLogic_$1 alloc] initWithComFqHalcyonLogicCheckVersionLogic_VersionCallback:callback]];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "checkVersionWithInt:withComFqHalcyonLogicCheckVersionLogic_VersionCallback:", "checkVersion", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicCheckVersionLogic = { "CheckVersionLogic", "com.fq.halcyon.logic", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicCheckVersionLogic;
}

@end

@interface ComFqHalcyonLogicCheckVersionLogic_VersionCallback : NSObject
@end

@implementation ComFqHalcyonLogicCheckVersionLogic_VersionCallback

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "callWithComFqHalcyonEntityVersion:", "call", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicCheckVersionLogic_VersionCallback = { "VersionCallback", "com.fq.halcyon.logic", "CheckVersionLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicCheckVersionLogic_VersionCallback;
}

@end

@implementation ComFqHalcyonLogicCheckVersionLogic_$1


#line 33
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 34
  [((id<ComFqHalcyonLogicCheckVersionLogic_VersionCallback>) nil_chk(val$callback_)) callWithComFqHalcyonEntityVersion:nil];
}


#line 37
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 38
  if (responseCode == 0 && type == 1) {
    ComFqHalcyonEntityVersion *version_ = [[ComFqHalcyonEntityVersion alloc] init];
    [version_ setAtttributeByjsonWithFQJSONObject:(FQJSONObject *) check_class_cast(results, [FQJSONObject class])];
    if ([version_ getVersionCode] > 0) {
      [((id<ComFqHalcyonLogicCheckVersionLogic_VersionCallback>) nil_chk(val$callback_)) callWithComFqHalcyonEntityVersion:version_];
      return;
    }
  }
  [((id<ComFqHalcyonLogicCheckVersionLogic_VersionCallback>) nil_chk(val$callback_)) callWithComFqHalcyonEntityVersion:nil];
}

- (id)initWithComFqHalcyonLogicCheckVersionLogic_VersionCallback:(id<ComFqHalcyonLogicCheckVersionLogic_VersionCallback>)capture$0 {
  val$callback_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogicCheckVersionLogic_VersionCallback:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callback_", NULL, 0x1012, "Lcom.fq.halcyon.logic.CheckVersionLogic$VersionCallback;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicCheckVersionLogic_$1 = { "$1", "com.fq.halcyon.logic", "CheckVersionLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogicCheckVersionLogic_$1;
}

@end
