//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Contacts.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityContacts_H_
#define _ComFqHalcyonEntityContacts_H_

@class FQJSONObject;
@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "Person.h"

#define ComFqHalcyonEntityContacts_serialVersionUID 1LL

@interface ComFqHalcyonEntityContacts : ComFqHalcyonEntityPerson {
 @public
  BOOL is_friend_;
  JavaUtilArrayList *mTags_;
  int userFriendId_;
  int relationId_;
  NSString *source_;
  int status_;
}

- (NSString *)getSource;

- (void)setSourceWithNSString:(NSString *)source;

- (int)getUserFriendId;

- (void)setTagsWithJavaUtilArrayList:(JavaUtilArrayList *)tags;

- (JavaUtilArrayList *)getTags;

- (void)addTagWithNSString:(NSString *)tag;

- (void)removeTagWithNSString:(NSString *)tag;

- (BOOL)isFriend;

- (int)getStatus;

- (void)setStatusWithInt:(int)status;

- (void)setRelationIdWithInt:(int)relationId;

- (int)getRelationId;

- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json;

- (FQJSONObject *)getJson;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityContacts *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityContacts_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityContacts, mTags_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityContacts, source_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityContacts, serialVersionUID, long long int)

#endif // _ComFqHalcyonEntityContacts_H_
