//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/ContactLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/ContactLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "ContactLogic.h"
#include "Contacts.h"
#include "FQHttpParams.h"
#include "HttpRequestPotocol.h"
#include "JSONArray.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "UriConstants.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"
#include "java/util/Iterator.h"


#line 20
@implementation ComFqHalcyonLogic2ContactLogic


#line 133
- (id)initWithComFqHalcyonLogic2ContactLogic_ContactLogicInterface:(id<ComFqHalcyonLogic2ContactLogic_ContactLogicInterface>)mIn
                                                           withInt:(int)userId {
  if (self = [super init]) {
    mHandle_ =
#line 131
    [[ComFqHalcyonLogic2ContactLogic_ContactLogicHandle alloc] initWithComFqHalcyonLogic2ContactLogic:self];
    
#line 134
    self->mInterface_ = mIn;
    
#line 135
    JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
    
#line 136
    (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:userId]];
    
#line 137
    FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
    
#line 138
    (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:[NSString stringWithFormat:@"%@/users/doctor_friends_list.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()] withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:mHandle_];
  }
  return self;
}

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2ContactLogic *)other {
  [super copyAllFieldsTo:other];
  other->mHandle_ = mHandle_;
  other->mHashPeerList_ = mHashPeerList_;
  other->mInterface_ = mInterface_;
  other->mPatientList_ = mPatientList_;
  other->mPeerListAll_ = mPeerListAll_;
  other->mPeerlist_ = mPeerlist_;
  other->mStuList_ = mStuList_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithComFqHalcyonLogic2ContactLogic_ContactLogicInterface:withInt:", "ContactLogic", NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mInterface_", NULL, 0x1, "Lcom.fq.halcyon.logic2.ContactLogic$ContactLogicInterface;", NULL,  },
    { "mStuList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "mPatientList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "mHashPeerList_", NULL, 0x2, "Ljava.util.HashMap;", NULL,  },
    { "mPeerlist_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "mPeerListAll_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "mHandle_", NULL, 0x1, "Lcom.fq.halcyon.logic2.ContactLogic$ContactLogicHandle;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2ContactLogic = { "ContactLogic", "com.fq.halcyon.logic2", NULL, 0x1, 1, methods, 7, fields, 0, NULL};
  return &_ComFqHalcyonLogic2ContactLogic;
}

@end

@interface ComFqHalcyonLogic2ContactLogic_ContactLogicInterface : NSObject
@end

@implementation ComFqHalcyonLogic2ContactLogic_ContactLogicInterface

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onDataReturnWithJavaUtilHashMap:", "onDataReturn", "V", 0x401, NULL },
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2ContactLogic_ContactLogicInterface = { "ContactLogicInterface", "com.fq.halcyon.logic2", "ContactLogic", 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2ContactLogic_ContactLogicInterface;
}

@end


#line 35
@implementation ComFqHalcyonLogic2ContactLogic_ContactLogicHandle


#line 38
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 39
  if (ComFqLibToolsConstants_get_contactsMap_() == nil) {
    
#line 41
    (void) ComFqLibToolsConstants_set_contactsList_([[JavaUtilArrayList alloc] init]);
    (void) ComFqLibToolsConstants_set_contactsMap_([[JavaUtilHashMap alloc] init]);
    (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_DOCTOR] withId:[[JavaUtilArrayList alloc] init]];
    (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_DOCTOR_STUDENT] withId:[[JavaUtilArrayList alloc] init]];
    (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_PATIENT] withId:[[JavaUtilArrayList alloc] init]];
  }
  if (this$0_->mInterface_ != nil) [this$0_->mInterface_ onErrorWithInt:code withJavaLangThrowable:e];
}


#line 51
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    this$0_->mStuList_ = [[JavaUtilArrayList alloc] init];
    this$0_->mPatientList_ = [[JavaUtilArrayList alloc] init];
    this$0_->mPeerListAll_ = [[JavaUtilArrayList alloc] init];
    this$0_->mHashPeerList_ = [[JavaUtilHashMap alloc] init];
    
#line 60
    if (ComFqLibToolsConstants_get_contactsList_() == nil) {
      (void) ComFqLibToolsConstants_set_contactsList_([[JavaUtilArrayList alloc] init]);
    }
    else {
      
#line 63
      [ComFqLibToolsConstants_get_contactsList_() clear];
    }
    if (ComFqLibToolsConstants_get_contactsMap_() == nil) {
      (void) ComFqLibToolsConstants_set_contactsMap_([[JavaUtilHashMap alloc] init]);
    }
    else {
      
#line 68
      [ComFqLibToolsConstants_get_contactsMap_() clear];
    }
    (void) [((JavaUtilHashMap *) nil_chk(ComFqLibToolsConstants_get_contactsMap_())) putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_DOCTOR] withId:this$0_->mPeerListAll_];
    (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_DOCTOR_STUDENT] withId:this$0_->mStuList_];
    (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_PATIENT] withId:this$0_->mPatientList_];
    
#line 74
    FQJSONArray *mArrayStu = [((FQJSONObject *) nil_chk(((FQJSONObject *) check_class_cast(results, [FQJSONObject class])))) optJSONArrayWithNSString:@"students"];
    FQJSONArray *mArrayPatient = [((FQJSONObject *) nil_chk(((FQJSONObject *) check_class_cast(results, [FQJSONObject class])))) optJSONArrayWithNSString:@"patients"];
    FQJSONArray *mArrayPeer = [((FQJSONObject *) nil_chk(((FQJSONObject *) check_class_cast(results, [FQJSONObject class])))) optJSONArrayWithNSString:@"peers"];
    
#line 78
    for (int i = 0; i < [((FQJSONArray *) nil_chk(mArrayPeer)) length]; i++) {
      FQJSONObject *object = [mArrayPeer optJSONObjectWithInt:i];
      id<JavaUtilIterator> keys = [((FQJSONObject *) nil_chk(object)) keys];
      while ([((id<JavaUtilIterator>) nil_chk(keys)) hasNext]) {
        NSString *key = [keys next];
        FQJSONArray *peersArray = [object optJSONArrayWithNSString:key];
        if (peersArray != nil) {
          this$0_->mPeerlist_ = [[JavaUtilArrayList alloc] init];
          for (int j = 0; j < [peersArray length]; j++) {
            ComFqHalcyonEntityContacts *mUser = [[ComFqHalcyonEntityContacts alloc] init];
            FQJSONObject *mJsonObject = [peersArray optJSONObjectWithInt:j];
            [mUser setAtttributeByjsonWithFQJSONObject:mJsonObject];
            [this$0_->mPeerlist_ addWithId:mUser];
            [this$0_->mPeerListAll_ addWithId:mUser];
            [((JavaUtilArrayList *) nil_chk(ComFqLibToolsConstants_get_contactsList_())) addWithId:mUser];
          }
          (void) [this$0_->mHashPeerList_ putWithId:key withId:this$0_->mPeerlist_];
        }
      }
    }
    
#line 99
    if (mArrayStu != nil) {
      for (int i = 0; i < [mArrayStu length]; i++) {
        ComFqHalcyonEntityContacts *mUser = [[ComFqHalcyonEntityContacts alloc] init];
        [mUser setAtttributeByjsonWithFQJSONObject:[mArrayStu optJSONObjectWithInt:i]];
        [this$0_->mStuList_ addWithId:mUser];
        [((JavaUtilArrayList *) nil_chk(ComFqLibToolsConstants_get_contactsList_())) addWithId:mUser];
      }
    }
    
#line 108
    for (int i = 0; i < [((FQJSONArray *) nil_chk(mArrayPatient)) length]; i++) {
      ComFqHalcyonEntityContacts *mUser = [[ComFqHalcyonEntityContacts alloc] init];
      [mUser setAtttributeByjsonWithFQJSONObject:[mArrayPatient optJSONObjectWithInt:i]];
      [this$0_->mPatientList_ addWithId:mUser];
      [((JavaUtilArrayList *) nil_chk(ComFqLibToolsConstants_get_contactsList_())) addWithId:mUser];
    }
    
#line 115
    if (this$0_->mInterface_ != nil) [this$0_->mInterface_ onDataReturnWithJavaUtilHashMap:this$0_->mHashPeerList_];
  }
  else {
    
#line 117
    if (ComFqLibToolsConstants_get_contactsMap_() == nil) {
      
#line 119
      (void) ComFqLibToolsConstants_set_contactsList_([[JavaUtilArrayList alloc] init]);
      (void) ComFqLibToolsConstants_set_contactsMap_([[JavaUtilHashMap alloc] init]);
      (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_DOCTOR] withId:[[JavaUtilArrayList alloc] init]];
      (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_DOCTOR_STUDENT] withId:[[JavaUtilArrayList alloc] init]];
      (void) [ComFqLibToolsConstants_get_contactsMap_() putWithId:[JavaLangInteger valueOfWithInt:ComFqLibToolsConstants_ROLE_PATIENT] withId:[[JavaUtilArrayList alloc] init]];
    }
    
#line 126
    if (this$0_->mInterface_ != nil) [this$0_->mInterface_ onErrorWithInt:responseCode withJavaLangThrowable:[[JavaLangThrowable alloc] initWithNSString:msg]];
  }
}

- (id)initWithComFqHalcyonLogic2ContactLogic:(ComFqHalcyonLogic2ContactLogic *)outer$ {
  this$0_ = outer$;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2ContactLogic:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.ContactLogic;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2ContactLogic_ContactLogicHandle = { "ContactLogicHandle", "com.fq.halcyon.logic2", "ContactLogic", 0x1, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2ContactLogic_ContactLogicHandle;
}

@end
