//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Contacts.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Contacts.java"

#include "Contacts.h"
#include "JSONArray.h"
#include "JSONException.h"
#include "JSONObject.h"
#include "java/util/ArrayList.h"


#line 9
@implementation ComFqHalcyonEntityContacts


#line 25
- (NSString *)getSource {
  
#line 26
  if (source_ == nil || [@"" isEqual:source_]) return @"\u8d26\u53f7\u67e5\u8be2";
  return source_;
}


#line 30
- (void)setSourceWithNSString:(NSString *)source {
  
#line 31
  self->source_ = source;
}


#line 34
- (int)getUserFriendId {
  
#line 35
  return userFriendId_;
}


#line 38
- (void)setTagsWithJavaUtilArrayList:(JavaUtilArrayList *)tags {
  
#line 39
  mTags_ = tags;
}


#line 42
- (JavaUtilArrayList *)getTags {
  
#line 43
  if (mTags_ == nil) mTags_ = [[JavaUtilArrayList alloc] init];
  return mTags_;
}


#line 47
- (void)addTagWithNSString:(NSString *)tag {
  
#line 48
  if (tag == nil || [@"" isEqual:tag])
#line 49
  return;
  if (mTags_ == nil) {
    mTags_ = [[JavaUtilArrayList alloc] init];
    [mTags_ addWithId:tag];
  }
  else {
    
#line 54
    BOOL ishave = NO;
    for (NSString * __strong tg in mTags_) {
      if ([((NSString *) nil_chk(tag)) isEqual:tg]) {
        ishave = YES;
        break;
      }
    }
    if (!ishave)
#line 62
    [mTags_ addWithId:tag];
  }
}


#line 66
- (void)removeTagWithNSString:(NSString *)tag {
  
#line 67
  if (tag == nil || [@"" isEqual:tag])
#line 68
  return;
  if (mTags_ == nil)
#line 70
  return;
  for (NSString * __strong tg in nil_chk(mTags_)) {
    if ([((NSString *) nil_chk(tag)) isEqual:tg]) {
      [mTags_ removeWithId:tg];
      break;
    }
  }
}


#line 79
- (BOOL)isFriend {
  
#line 80
  return is_friend_;
}


#line 83
- (int)getStatus {
  
#line 84
  return status_;
}


#line 87
- (void)setStatusWithInt:(int)status {
  
#line 88
  self->status_ = status;
}


#line 91
- (void)setRelationIdWithInt:(int)relationId {
  
#line 92
  self->relationId_ = relationId;
}


#line 95
- (int)getRelationId {
  
#line 96
  return self->relationId_;
}


#line 100
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  [super setAtttributeByjsonWithFQJSONObject:json];
  self->is_friend_ = [((FQJSONObject *) nil_chk(json)) optBooleanWithNSString:@"is_friend" withBoolean:NO];
  self->status_ = [json optIntWithNSString:@"status" withInt:-1];
  self->userFriendId_ = [json optIntWithNSString:@"userFriendId"];
  self->source_ = [json optStringWithNSString:@"source"];
  self->relationId_ = [json optIntWithNSString:@"user_doctor_relation_id"];
  
#line 108
  FQJSONArray *tags = [json optJSONArrayWithNSString:@"tags"];
  if (tags != nil) {
    mTags_ = [[JavaUtilArrayList alloc] init];
    for (int i = 0; i < [tags length]; i++) {
      FQJSONObject *tagJson = [tags optJSONObjectWithInt:i];
      [mTags_ addWithId:[((FQJSONObject *) nil_chk(tagJson)) optStringWithNSString:@"title"]];
    }
  }
}

- (FQJSONObject *)getJson {
  
#line 120
  FQJSONObject *json = [super getJson];
  @try {
    (void) [((FQJSONObject *) nil_chk(json)) putWithNSString:@"is_friend" withBoolean:is_friend_];
    (void) [json putWithNSString:@"status" withInt:status_];
    (void) [json putWithNSString:@"userFriendId" withInt:userFriendId_];
  }
  @catch (FQJSONException *e) {
    [((FQJSONException *) nil_chk(e)) printStackTrace];
  }
  return json;
}

- (id)init {
  return [super init];
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityContacts *)other {
  [super copyAllFieldsTo:other];
  other->is_friend_ = is_friend_;
  other->mTags_ = mTags_;
  other->relationId_ = relationId_;
  other->source_ = source_;
  other->status_ = status_;
  other->userFriendId_ = userFriendId_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getSource", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setSourceWithNSString:", "setSource", "V", 0x1, NULL },
    { "getUserFriendId", NULL, "I", 0x1, NULL },
    { "setTagsWithJavaUtilArrayList:", "setTags", "V", 0x1, NULL },
    { "getTags", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "addTagWithNSString:", "addTag", "V", 0x1, NULL },
    { "removeTagWithNSString:", "removeTag", "V", 0x1, NULL },
    { "isFriend", NULL, "Z", 0x1, NULL },
    { "getStatus", NULL, "I", 0x1, NULL },
    { "setStatusWithInt:", "setStatus", "V", 0x1, NULL },
    { "setRelationIdWithInt:", "setRelationId", "V", 0x1, NULL },
    { "getRelationId", NULL, "I", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "getJson", NULL, "Lcom.fq.lib.json.JSONObject;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_Contacts_", "serialVersionUID", 0x1a, "J", NULL, .constantValue.asLong = ComFqHalcyonEntityContacts_serialVersionUID },
    { "is_friend_", NULL, 0x2, "Z", NULL,  },
    { "mTags_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "userFriendId_", NULL, 0x2, "I", NULL,  },
    { "relationId_", NULL, 0x2, "I", NULL,  },
    { "source_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "status_", NULL, 0x2, "I", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityContacts = { "Contacts", "com.fq.halcyon.entity", NULL, 0x1, 15, methods, 7, fields, 0, NULL};
  return &_ComFqHalcyonEntityContacts;
}

@end
