//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/CreatePatientLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2CreatePatientLogic_H_
#define _ComFqHalcyonLogic2CreatePatientLogic_H_

@class ComFqHalcyonEntityPatient;
@class ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalLogicHandle;
@class JavaLangThrowable;
@protocol ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack;

#import "JreEmulation.h"
#include "HalcyonHttpResponseHandle.h"

@interface ComFqHalcyonLogic2CreatePatientLogic : NSObject {
 @public
  id<ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack> onCallBack_;
  ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalLogicHandle *mHandle_;
}

- (id)initWithComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack:(id<ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack>)onCallBack;

- (void)createMedicalWithNSString:(NSString *)patientName;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2CreatePatientLogic *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2CreatePatientLogic_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2CreatePatientLogic, onCallBack_, id<ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack>)
J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2CreatePatientLogic, mHandle_, ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalLogicHandle *)

@protocol ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack < NSObject, JavaObject >

- (void)createMedicalErrorWithInt:(int)code
                     withNSString:(NSString *)msg;

- (void)createMedicalSuccessWithInt:(int)code
      withComFqHalcyonEntityPatient:(ComFqHalcyonEntityPatient *)medical;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalCallBack_init() {}

@interface ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalLogicHandle : HalcyonHttpResponseHandle {
 @public
  ComFqHalcyonLogic2CreatePatientLogic *this$0_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2CreatePatientLogic:(ComFqHalcyonLogic2CreatePatientLogic *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalLogicHandle_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2CreatePatientLogic_CreateMedicalLogicHandle, this$0_, ComFqHalcyonLogic2CreatePatientLogic *)

#endif // _ComFqHalcyonLogic2CreatePatientLogic_H_
