//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/CreateRecordLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/CreateRecordLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "CreateRecordLogic.h"
#include "FQHttpParams.h"
#include "HttpRequestPotocol.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "Record.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/HashMap.h"


#line 18
@implementation ComFqHalcyonLogic2CreateRecordLogic


#line 28
- (id)initWithComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack:(id<ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack>)onCallBack {
  if (self = [super init]) {
    
#line 29
    self->onCallBack_ = onCallBack;
    
#line 30
    mHandle_ = [[ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderHandle alloc] initWithComFqHalcyonLogic2CreateRecordLogic:self];
  }
  return self;
}


#line 39
- (void)createRecordFolderWithNSString:(NSString *)recordName
                               withInt:(int)patientId
                               withInt:(int)recordCategory {
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"patient_id" withId:[JavaLangInteger valueOfWithInt:patientId]];
  (void) [map putWithId:@"record_name" withId:recordName];
  (void) [map putWithId:@"record_category" withId:[JavaLangInteger valueOfWithInt:recordCategory]];
  FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
  NSString *uri = [NSString stringWithFormat:@"%@/record/create.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  
#line 48
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:uri withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:mHandle_];
}

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2CreateRecordLogic *)other {
  [super copyAllFieldsTo:other];
  other->mHandle_ = mHandle_;
  other->onCallBack_ = onCallBack_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack:", "CreateRecordLogic", NULL, 0x1, NULL },
    { "createRecordFolderWithNSString:withInt:withInt:", "createRecordFolder", "V", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "onCallBack_", NULL, 0x2, "Lcom.fq.halcyon.logic2.CreateRecordLogic$CreateRecordFolderCallBack;", NULL,  },
    { "mHandle_", NULL, 0x2, "Lcom.fq.halcyon.logic2.CreateRecordLogic$CreateRecordFolderHandle;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2CreateRecordLogic = { "CreateRecordLogic", "com.fq.halcyon.logic2", NULL, 0x1, 2, methods, 2, fields, 0, NULL};
  return &_ComFqHalcyonLogic2CreateRecordLogic;
}

@end

@interface ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack : NSObject
@end

@implementation ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onCreateFolderErrorWithInt:withNSString:", "onCreateFolderError", "V", 0x401, NULL },
    { "onCreateFolderSuccessWithInt:withComFqHalcyonEntityRecord:", "onCreateFolderSuccess", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack = { "CreateRecordFolderCallBack", "com.fq.halcyon.logic2", "CreateRecordLogic", 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack;
}

@end


#line 51
@implementation ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderHandle


#line 54
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 55
  [((id<ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack>) nil_chk(this$0_->onCallBack_)) onCreateFolderErrorWithInt:code withNSString:[((JavaLangThrowable *) nil_chk(e)) getMessage]];
}


#line 59
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    FQJSONObject *json = (FQJSONObject *) check_class_cast(results, [FQJSONObject class]);
    ComFqHalcyonEntityRecord *record = [[ComFqHalcyonEntityRecord alloc] init];
    [record setAtttributeByjsonWithFQJSONObject:json];
    [((id<ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack>) nil_chk(this$0_->onCallBack_)) onCreateFolderSuccessWithInt:responseCode withComFqHalcyonEntityRecord:record];
  }
  else {
    
#line 67
    [((id<ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderCallBack>) nil_chk(this$0_->onCallBack_)) onCreateFolderErrorWithInt:responseCode withNSString:msg];
  }
}

- (id)initWithComFqHalcyonLogic2CreateRecordLogic:(ComFqHalcyonLogic2CreateRecordLogic *)outer$ {
  this$0_ = outer$;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2CreateRecordLogic:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.CreateRecordLogic;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderHandle = { "CreateRecordFolderHandle", "com.fq.halcyon.logic2", "CreateRecordLogic", 0x0, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2CreateRecordLogic_CreateRecordFolderHandle;
}

@end
