//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Doctor.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityDoctor_H_
#define _ComFqHalcyonEntityDoctor_H_

#import "JreEmulation.h"
#include "User.h"

#define ComFqHalcyonEntityDoctor_serialVersionUID 1LL

@interface ComFqHalcyonEntityDoctor : ComFqHalcyonEntityUser {
 @public
  int doctorId_;
}

- (int)getDoctorId;

- (void)setDoctorIdWithInt:(int)doctorId;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityDoctor *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityDoctor_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityDoctor, serialVersionUID, long long int)

#endif // _ComFqHalcyonEntityDoctor_H_
