//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/ExpenseDetailLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/ExpenseDetailLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "ExpenseDetailLogic.h"
#include "FQHttpParams.h"
#include "HttpRequestPotocol.h"
#include "JSONArray.h"
#include "JSONException.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "ScoreDetail.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"


#line 23
@implementation ComFqHalcyonLogic2ExpenseDetailLogic


#line 40
- (id)initWithInt:(int)page
          withInt:(int)pageSize
withComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack:(id<ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack>)onCallBack {
  if (self = [super init]) {
    mDetailList_ =
#line 26
    [[JavaUtilArrayList alloc] init];
    mHandle_ =
#line 77
    [[ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicHandle alloc] initWithComFqHalcyonLogic2ExpenseDetailLogic:self];
    
#line 41
    self->onCallBack_ = onCallBack;
    
#line 42
    JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
    
#line 43
    (void) [map putWithId:@"doctor_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getDoctorId]]];
    
#line 44
    (void) [map putWithId:@"page" withId:[JavaLangInteger valueOfWithInt:page]];
    
#line 45
    (void) [map putWithId:@"page_size" withId:[JavaLangInteger valueOfWithInt:pageSize]];
    
#line 46
    FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
    
#line 47
    (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:[NSString stringWithFormat:@"%@/doctors/getDpList.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()] withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:mHandle_];
  }
  return self;
}

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2ExpenseDetailLogic *)other {
  [super copyAllFieldsTo:other];
  other->mDetailList_ = mDetailList_;
  other->mHandle_ = mHandle_;
  other->onCallBack_ = onCallBack_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithInt:withInt:withComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack:", "ExpenseDetailLogic", NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mDetailList_", NULL, 0x2, "Ljava.util.List;", NULL,  },
    { "onCallBack_", NULL, 0x1, "Lcom.fq.halcyon.logic2.ExpenseDetailLogic$ExpenseDetailLogicCallBack;", NULL,  },
    { "mHandle_", NULL, 0x1, "Lcom.fq.halcyon.logic2.ExpenseDetailLogic$ExpenseDetailLogicHandle;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2ExpenseDetailLogic = { "ExpenseDetailLogic", "com.fq.halcyon.logic2", NULL, 0x1, 1, methods, 3, fields, 0, NULL};
  return &_ComFqHalcyonLogic2ExpenseDetailLogic;
}

@end

@interface ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack : NSObject
@end

@implementation ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorCallBackWithInt:withNSString:", "onErrorCallBack", "V", 0x401, NULL },
    { "onResultCallBackWithInt:withJavaUtilList:", "onResultCallBack", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack = { "ExpenseDetailLogicCallBack", "com.fq.halcyon.logic2", "ExpenseDetailLogic", 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack;
}

@end


#line 50
@implementation ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicHandle


#line 53
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 54
  [((id<ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack>) nil_chk(this$0_->onCallBack_)) onErrorCallBackWithInt:code withNSString:[((JavaLangThrowable *) nil_chk(e)) getMessage]];
}


#line 58
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0 && type == 2) {
    FQJSONArray *jsonArray = (FQJSONArray *) check_class_cast(results, [FQJSONArray class]);
    int count = [((FQJSONArray *) nil_chk(jsonArray)) length];
    for (int i = 0; i < count; i++) {
      @try {
        ComFqHalcyonEntityScoreDetail *mDetail = [[ComFqHalcyonEntityScoreDetail alloc] init];
        [mDetail setAtttributeByjsonWithFQJSONObject:[jsonArray getJSONObjectWithInt:i]];
        [((id<JavaUtilList>) nil_chk(this$0_->mDetailList_)) addWithId:mDetail];
      }
      @catch (
#line 68
      FQJSONException *e) {
        [((FQJSONException *) nil_chk(e)) printStackTrace];
      }
    }
    [((id<ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicCallBack>) nil_chk(this$0_->onCallBack_)) onResultCallBackWithInt:responseCode withJavaUtilList:this$0_->mDetailList_];
  }
}

- (id)initWithComFqHalcyonLogic2ExpenseDetailLogic:(ComFqHalcyonLogic2ExpenseDetailLogic *)outer$ {
  this$0_ = outer$;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2ExpenseDetailLogic:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.ExpenseDetailLogic;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicHandle = { "ExpenseDetailLogicHandle", "com.fq.halcyon.logic2", "ExpenseDetailLogic", 0x1, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2ExpenseDetailLogic_ExpenseDetailLogicHandle;
}

@end
