//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/FollowUp.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityFollowUp_H_
#define _ComFqHalcyonEntityFollowUp_H_

@class FQJSONObject;
@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "HalcyonEntity.h"

#define ComFqHalcyonEntityFollowUp_serialVersionUID 1LL

@interface ComFqHalcyonEntityFollowUp : ComFqHalcyonEntityHalcyonEntity {
 @public
  NSString *mTips_;
  JavaUtilArrayList *mMemberList_;
  JavaUtilArrayList *mFriendsList_;
  NSString *mFolloUpTempleName_;
  int mDoctorId_;
  JavaUtilArrayList *mFollowUpItemsList_;
  JavaUtilArrayList *mMessageList_;
  NSString *mFromDate_;
  NSString *mId_;
}

- (void)test;

- (NSString *)getmTips;

- (void)setmTipsWithNSString:(NSString *)mTips;

- (JavaUtilArrayList *)getmMemberList;

- (void)setmMemberListWithJavaUtilArrayList:(JavaUtilArrayList *)mMemberList;

- (NSString *)getmFolloUpTempleName;

- (void)setmFolloUpTempleNameWithNSString:(NSString *)mFolloUpTempleName;

- (int)getmDoctorId;

- (void)setmDoctorIdWithInt:(int)mDoctorId;

- (JavaUtilArrayList *)getmFollowUpItemsList;

- (void)setmFollowUpItemsListWithJavaUtilArrayList:(JavaUtilArrayList *)mFollowUpItemsList;

- (JavaUtilArrayList *)getmFriendsList;

- (void)setmFriendsListWithJavaUtilArrayList:(JavaUtilArrayList *)mFriendsList;

- (JavaUtilArrayList *)getmMessageList;

- (void)setmMessageListWithJavaUtilArrayList:(JavaUtilArrayList *)mMessageList;

- (NSString *)getmFromDate;

- (void)setmFromDateWithNSString:(NSString *)mFromDate;

- (NSString *)getmId;

- (void)setmIdWithNSString:(NSString *)mId;

- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityFollowUp *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityFollowUp_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mTips_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mMemberList_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mFriendsList_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mFolloUpTempleName_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mFollowUpItemsList_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mMessageList_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mFromDate_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityFollowUp, mId_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityFollowUp, serialVersionUID, long long int)

#endif // _ComFqHalcyonEntityFollowUp_H_
