//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/potocol/FQHttpResponseHandle.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/potocol/FQHttpResponseHandle.java"

#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "java/lang/Throwable.h"
#import "FQHttpResponseHandle.h"

@interface FQHttpResponseHandle : NSObject
@end

@implementation FQHttpResponseHandle

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x401, NULL },
    { "handleResponseWithByteArray:", "handleResponse", "V", 0x401, NULL },
    { "getRequestHeaders", NULL, "[Lcom.fq.http.async.FQHeader;", 0x401, NULL },
    { "setRequestHeadersWithComFqHttpAsyncFQHeaderArray:", "setRequestHeaders", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _FQHttpResponseHandle = { "FQHttpResponseHandle", "com.fq.http.potocol", NULL, 0x201, 4, methods, 0, NULL, 0, NULL};
  return &_FQHttpResponseHandle;
}

@end
