//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/potocol/FQJsonResponseHandle.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpPotocolFQJsonResponseHandle_H_
#define _ComFqHttpPotocolFQJsonResponseHandle_H_

@class FQJSONObject;
@class IOSByteArray;

#import "JreEmulation.h"
#include "FQBinaryResponseHandle.h"

@interface FQJsonResponseHandle : FQBinaryResponseHandle {
}

- (void)handleBinaryDataWithByteArray:(IOSByteArray *)data;

- (void)handleJsonWithFQJSONObject:(FQJSONObject *)json;

- (id)init;

@end

__attribute__((always_inline)) inline void FQJsonResponseHandle_init() {}

#endif // _ComFqHttpPotocolFQJsonResponseHandle_H_
