//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DoctorPlus_ios/Java_implement/com/fq/http/async/uploadloop/FQLooper.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpAsyncUploadloopFQLooper_H_
#define _ComFqHttpAsyncUploadloopFQLooper_H_

@class ComFqHttpAsyncUploadloopFQLoopQueue;
@class ComFqHttpAsyncUploadloopLoopCell;
@class ComFqHttpAsyncUploadloopLoopCellHandle;
@class JavaLangThread;
@class JavaUtilArrayList;

#import "JreEmulation.h"
#include "java/lang/Runnable.h"

@interface ComFqHttpAsyncUploadloopFQLooper : NSObject {
 @public
  ComFqHttpAsyncUploadloopFQLoopQueue *mQueue_;
  JavaLangThread *mLooperThread_;
  int mInterval_;
  id<JavaLangRunnable> mWorker_;
  BOOL mIsPause_;
}

- (id)init;

- (id)initWithInt:(int)interval;

- (void)pushWithComFqHttpAsyncUploadloopLoopCellHandle:(ComFqHttpAsyncUploadloopLoopCellHandle *)hanlde;

- (void)pushWithComFqHttpAsyncUploadloopLoopCell:(ComFqHttpAsyncUploadloopLoopCell *)cell;

- (void)stop;

- (void)start;

- (JavaUtilArrayList *)getAll;

- (int)getUploadCount;

- (int)getUploadUserCount;

- (JavaUtilArrayList *)getUploadArray;

- (JavaUtilArrayList *)getUploadCellsWithInt:(int)recordId;

- (void)cancelUploadCellWithInt:(int)recordId
                   withNSString:(NSString *)uuid;

- (void)copyAllFieldsTo:(ComFqHttpAsyncUploadloopFQLooper *)other;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncUploadloopFQLooper_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopFQLooper, mQueue_, ComFqHttpAsyncUploadloopFQLoopQueue *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopFQLooper, mLooperThread_, JavaLangThread *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopFQLooper, mWorker_, id<JavaLangRunnable>)

@interface ComFqHttpAsyncUploadloopFQLooper_$1 : NSObject < JavaLangRunnable > {
 @public
  ComFqHttpAsyncUploadloopFQLooper *this$0_;
}

- (void)run;

- (id)initWithComFqHttpAsyncUploadloopFQLooper:(ComFqHttpAsyncUploadloopFQLooper *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncUploadloopFQLooper_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopFQLooper_$1, this$0_, ComFqHttpAsyncUploadloopFQLooper *)

#endif // _ComFqHttpAsyncUploadloopFQLooper_H_
