//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic/GetImagePathLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic/GetImagePathLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "FQHttpParams.h"
#include "GetImagePathLogic.h"
#include "HttpRequestPotocol.h"
#include "IOSClass.h"
#include "JSONArray.h"
#include "JSONException.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "PhotoRecord.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"


#line 18
@implementation ComFqHalcyonLogicGetImagePathLogic


#line 26
- (id)init {
  return [super init];
}


#line 29
- (id)initWithComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack:(id<ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack>)callback {
  if (self = [super init]) {
    
#line 30
    mCallback_ = callback;
  }
  return self;
}


#line 33
- (void)getImagePathWithInt:(int)recordItemId {
  
#line 34
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"record_item_id" withId:[JavaLangInteger valueOfWithInt:recordItemId]];
  
#line 38
  NSString *url = [NSString stringWithFormat:@"%@/record/item/get_image.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 41
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:[[ComFqHalcyonLogicGetImagePathLogic_$1 alloc] initWithComFqHalcyonLogicGetImagePathLogic:self]];
}


#line 76
- (void)getRecordImagesWithInt:(int)recordId
withComFqHalcyonLogicGetImagePathLogic_RecordImageCallback:(id<ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback>)callback {
  
#line 77
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"record_id" withId:[JavaLangInteger valueOfWithInt:recordId]];
  
#line 81
  NSString *url = [NSString stringWithFormat:@"%@/record/get_record_image.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 84
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:[[ComFqHalcyonLogicGetImagePathLogic_$2 alloc] initWithComFqHalcyonLogicGetImagePathLogic_RecordImageCallback:callback]];
}

- (void)copyAllFieldsTo:(ComFqHalcyonLogicGetImagePathLogic *)other {
  [super copyAllFieldsTo:other];
  other->mCallback_ = mCallback_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "GetImagePathLogic", NULL, 0x1, NULL },
    { "initWithComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack:", "GetImagePathLogic", NULL, 0x1, NULL },
    { "getImagePathWithInt:", "getImagePath", "V", 0x1, NULL },
    { "getRecordImagesWithInt:withComFqHalcyonLogicGetImagePathLogic_RecordImageCallback:", "getRecordImages", "V", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mCallback_", NULL, 0x2, "Lcom.fq.halcyon.logic.GetImagePathLogic$ImagePathCallBack;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicGetImagePathLogic = { "GetImagePathLogic", "com.fq.halcyon.logic", NULL, 0x1, 4, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogicGetImagePathLogic;
}

@end

@interface ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack : NSObject
@end

@implementation ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "dobackWithJavaUtilArrayList:", "doback", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack = { "ImagePathCallBack", "com.fq.halcyon.logic", "GetImagePathLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack;
}

@end

@interface ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback : NSObject
@end

@implementation ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "callRecrodImagesWithJavaUtilArrayList:", "callRecrodImages", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback = { "RecordImageCallback", "com.fq.halcyon.logic", "GetImagePathLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback;
}

@end

@implementation ComFqHalcyonLogicGetImagePathLogic_$1


#line 44
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 45
  [((id<ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack>) nil_chk(this$0_->mCallback_)) dobackWithJavaUtilArrayList:nil];
}


#line 49
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 50
  if (responseCode == 0 && type == 1) {
    FQJSONObject *json = (FQJSONObject *) check_class_cast(results, [FQJSONObject class]);
    @try {
      FQJSONArray *array = [((FQJSONObject *) nil_chk(((FQJSONObject *) check_class_cast(results, [FQJSONObject class])))) getJSONArrayWithNSString:@"photos"];
      JavaUtilArrayList *photos = [[JavaUtilArrayList alloc] init];
      for (int i = 0; i < [((FQJSONArray *) nil_chk(array)) length]; i++) {
        ComFqHalcyonEntityPhotoRecord *photo = [[ComFqHalcyonEntityPhotoRecord alloc] init];
        [photo setAtttributeByjsonWithFQJSONObject:[array getJSONObjectWithInt:i]];
        [photos addWithId:photo];
      }
      [((id<ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack>) nil_chk(this$0_->mCallback_)) dobackWithJavaUtilArrayList:photos];
    }
    @catch (
#line 61
    FQJSONException *e) {
      [((FQJSONException *) nil_chk(e)) printStackTrace];
      [((id<ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack>) nil_chk(this$0_->mCallback_)) dobackWithJavaUtilArrayList:nil];
    }
  }
  else {
    
#line 66
    [((id<ComFqHalcyonLogicGetImagePathLogic_ImagePathCallBack>) nil_chk(this$0_->mCallback_)) dobackWithJavaUtilArrayList:nil];
  }
}

- (id)initWithComFqHalcyonLogicGetImagePathLogic:(ComFqHalcyonLogicGetImagePathLogic *)outer$ {
  this$0_ = outer$;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogicGetImagePathLogic:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.halcyon.logic.GetImagePathLogic;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicGetImagePathLogic_$1 = { "$1", "com.fq.halcyon.logic", "GetImagePathLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogicGetImagePathLogic_$1;
}

@end

@implementation ComFqHalcyonLogicGetImagePathLogic_$2


#line 86
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 87
  [((id<ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback>) nil_chk(val$callback_)) callRecrodImagesWithJavaUtilArrayList:nil];
}


#line 91
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 92
  if (responseCode == 0 && type == 1) {
    FQJSONObject *json = (FQJSONObject *) check_class_cast(results, [FQJSONObject class]);
    @try {
      FQJSONArray *array = [((FQJSONObject *) nil_chk(((FQJSONObject *) check_class_cast(results, [FQJSONObject class])))) getJSONArrayWithNSString:@"photos"];
      JavaUtilArrayList *photos = [[JavaUtilArrayList alloc] init];
      for (int i = 0; i < [((FQJSONArray *) nil_chk(array)) length]; i++) {
        ComFqHalcyonEntityPhotoRecord *photo = [[ComFqHalcyonEntityPhotoRecord alloc] init];
        [photo setAtttributeByjsonWithFQJSONObject:[array getJSONObjectWithInt:i]];
        [photos addWithId:photo];
      }
      [((id<ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback>) nil_chk(val$callback_)) callRecrodImagesWithJavaUtilArrayList:photos];
    }
    @catch (
#line 103
    FQJSONException *e) {
      [((FQJSONException *) nil_chk(e)) printStackTrace];
      [((id<ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback>) nil_chk(val$callback_)) callRecrodImagesWithJavaUtilArrayList:nil];
    }
  }
  else {
    
#line 108
    [((id<ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback>) nil_chk(val$callback_)) callRecrodImagesWithJavaUtilArrayList:nil];
  }
}

- (id)initWithComFqHalcyonLogicGetImagePathLogic_RecordImageCallback:(id<ComFqHalcyonLogicGetImagePathLogic_RecordImageCallback>)capture$0 {
  val$callback_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogicGetImagePathLogic_RecordImageCallback:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callback_", NULL, 0x1012, "Lcom.fq.halcyon.logic.GetImagePathLogic$RecordImageCallback;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicGetImagePathLogic_$2 = { "$2", "com.fq.halcyon.logic", "GetImagePathLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogicGetImagePathLogic_$2;
}

@end
