//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/GetRecordListLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2GetRecordListLogic_H_
#define _ComFqHalcyonLogic2GetRecordListLogic_H_

@class JavaLangThrowable;
@class JavaUtilArrayList;
@protocol ComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack;

#import "JreEmulation.h"
#include "HalcyonHttpResponseHandle.h"

@interface ComFqHalcyonLogic2GetRecordListLogic : NSObject {
 @public
  JavaUtilArrayList *mRecordList_;
  id<ComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack> onCallBack_;
}

- (id)initWithComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack:(id<ComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack>)onCallBack;

- (void)getRecordListWithInt:(int)patientId
                     withInt:(int)page
                     withInt:(int)pageSize;

- (void)getRecordListWithInt:(int)patientId;

- (void)getRecordListWithInt:(int)patientId
                withNSString:(NSString *)recordName;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2GetRecordListLogic *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordListLogic_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordListLogic, mRecordList_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordListLogic, onCallBack_, id<ComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack>)

@protocol ComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack < NSObject, JavaObject >

- (void)onGetRecordListErrorWithInt:(int)code
                       withNSString:(NSString *)msg;

- (void)onGetRecordListWithJavaUtilArrayList:(JavaUtilArrayList *)mRecordList;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordListLogic_GetRecordListCallBack_init() {}

@interface ComFqHalcyonLogic2GetRecordListLogic_GetRecordListHandle : HalcyonHttpResponseHandle {
 @public
  ComFqHalcyonLogic2GetRecordListLogic *this$0_;
  int mPatientId_;
  int mPage_;
}

- (id)initWithComFqHalcyonLogic2GetRecordListLogic:(ComFqHalcyonLogic2GetRecordListLogic *)outer$
                                           withInt:(int)patientId
                                           withInt:(int)page;

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleCacheWithInt:(int)responseCode
              withNSString:(NSString *)msg
                   withInt:(int)type
                    withId:(id)results
               withBoolean:(BOOL)fromCache;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2GetRecordListLogic_GetRecordListHandle *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordListLogic_GetRecordListHandle_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordListLogic_GetRecordListHandle, this$0_, ComFqHalcyonLogic2GetRecordListLogic *)

#endif // _ComFqHalcyonLogic2GetRecordListLogic_H_
