//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/GetRecordItemLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2GetRecordItemLogic_H_
#define _ComFqHalcyonLogic2GetRecordItemLogic_H_

@class ComFqHalcyonEntityRecordItem;
@class JavaLangThrowable;
@protocol ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack;
@protocol ComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack;

#import "JreEmulation.h"
#include "HalcyonHttpResponseHandle.h"
#include "java/lang/Runnable.h"

@interface ComFqHalcyonLogic2GetRecordItemLogic : NSObject {
 @public
  id<ComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack> mCallback_;
}

- (id)init;

- (id)initWithComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack:(id<ComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack>)callback;

- (void)loadRecordItemWithInt:(int)recordInfoId;

- (void)modifyRecordItemWithInt:(int)recordInfoId
                        withInt:(int)type
                         withId:(id)obj
withComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack:(id<ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack>)callback;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2GetRecordItemLogic *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordItemLogic_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordItemLogic, mCallback_, id<ComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack>)

@protocol ComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack < NSObject, JavaObject >

- (void)doRecordItemBackWithComFqHalcyonEntityRecordItem:(ComFqHalcyonEntityRecordItem *)recordItem;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordItemLogic_RecordItemCallBack_init() {}

@protocol ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack < NSObject, JavaObject >

- (void)doBackWithBoolean:(BOOL)isb;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack_init() {}

@interface ComFqHalcyonLogic2GetRecordItemLogic_$1 : HalcyonHttpResponseHandle {
 @public
  ComFqHalcyonLogic2GetRecordItemLogic *this$0_;
  int val$recordInfoId_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2GetRecordItemLogic:(ComFqHalcyonLogic2GetRecordItemLogic *)outer$
                                           withInt:(int)capture$0;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordItemLogic_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordItemLogic_$1, this$0_, ComFqHalcyonLogic2GetRecordItemLogic *)

@interface ComFqHalcyonLogic2GetRecordItemLogic_$1_$1 : NSObject < JavaLangRunnable > {
 @public
  ComFqHalcyonLogic2GetRecordItemLogic_$1 *this$0_;
  ComFqHalcyonEntityRecordItem *val$item_;
}

- (void)run;

- (id)initWithComFqHalcyonLogic2GetRecordItemLogic_$1:(ComFqHalcyonLogic2GetRecordItemLogic_$1 *)outer$
                     withComFqHalcyonEntityRecordItem:(ComFqHalcyonEntityRecordItem *)capture$0;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordItemLogic_$1_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordItemLogic_$1_$1, this$0_, ComFqHalcyonLogic2GetRecordItemLogic_$1 *)
J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordItemLogic_$1_$1, val$item_, ComFqHalcyonEntityRecordItem *)

@interface ComFqHalcyonLogic2GetRecordItemLogic_$2 : HalcyonHttpResponseHandle {
 @public
  id<ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack> val$callback_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack:(id<ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack>)capture$0;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2GetRecordItemLogic_$2_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2GetRecordItemLogic_$2, val$callback_, id<ComFqHalcyonLogic2GetRecordItemLogic_ModifyItemCallBack>)

#endif // _ComFqHalcyonLogic2GetRecordItemLogic_H_
