//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/pinyin4j/HanyuPinyinOutputFormat.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqLibPinyin4jHanyuPinyinOutputFormat_H_
#define _ComFqLibPinyin4jHanyuPinyinOutputFormat_H_

@class ComFqLibPinyin4jHanyuPinyinCaseType;
@class ComFqLibPinyin4jHanyuPinyinToneType;
@class ComFqLibPinyin4jHanyuPinyinVCharType;

#import "JreEmulation.h"

@interface ComFqLibPinyin4jHanyuPinyinOutputFormat : NSObject {
 @public
  ComFqLibPinyin4jHanyuPinyinVCharType *vCharType_;
  ComFqLibPinyin4jHanyuPinyinCaseType *caseType_;
  ComFqLibPinyin4jHanyuPinyinToneType *toneType_;
}

- (id)init;

- (void)restoreDefault;

- (ComFqLibPinyin4jHanyuPinyinCaseType *)getCaseType;

- (void)setCaseTypeWithComFqLibPinyin4jHanyuPinyinCaseType:(ComFqLibPinyin4jHanyuPinyinCaseType *)caseType;

- (ComFqLibPinyin4jHanyuPinyinToneType *)getToneType;

- (void)setToneTypeWithComFqLibPinyin4jHanyuPinyinToneType:(ComFqLibPinyin4jHanyuPinyinToneType *)toneType;

- (ComFqLibPinyin4jHanyuPinyinVCharType *)getVCharType;

- (void)setVCharTypeWithComFqLibPinyin4jHanyuPinyinVCharType:(ComFqLibPinyin4jHanyuPinyinVCharType *)charType;

- (void)copyAllFieldsTo:(ComFqLibPinyin4jHanyuPinyinOutputFormat *)other;

@end

__attribute__((always_inline)) inline void ComFqLibPinyin4jHanyuPinyinOutputFormat_init() {}

J2OBJC_FIELD_SETTER(ComFqLibPinyin4jHanyuPinyinOutputFormat, vCharType_, ComFqLibPinyin4jHanyuPinyinVCharType *)
J2OBJC_FIELD_SETTER(ComFqLibPinyin4jHanyuPinyinOutputFormat, caseType_, ComFqLibPinyin4jHanyuPinyinCaseType *)
J2OBJC_FIELD_SETTER(ComFqLibPinyin4jHanyuPinyinOutputFormat, toneType_, ComFqLibPinyin4jHanyuPinyinToneType *)

#endif // _ComFqLibPinyin4jHanyuPinyinOutputFormat_H_
