//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/pinyin4j/HanyuPinyinCaseType.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqLibPinyin4jHanyuPinyinCaseType_H_
#define _ComFqLibPinyin4jHanyuPinyinCaseType_H_

#import "JreEmulation.h"

@interface ComFqLibPinyin4jHanyuPinyinCaseType : NSObject {
 @public
  NSString *name_;
}

- (NSString *)getName;

- (void)setNameWithNSString:(NSString *)name;

- (id)initWithNSString:(NSString *)name;

- (void)copyAllFieldsTo:(ComFqLibPinyin4jHanyuPinyinCaseType *)other;

@end

FOUNDATION_EXPORT BOOL ComFqLibPinyin4jHanyuPinyinCaseType_initialized;
J2OBJC_STATIC_INIT(ComFqLibPinyin4jHanyuPinyinCaseType)

J2OBJC_FIELD_SETTER(ComFqLibPinyin4jHanyuPinyinCaseType, name_, NSString *)

FOUNDATION_EXPORT ComFqLibPinyin4jHanyuPinyinCaseType *ComFqLibPinyin4jHanyuPinyinCaseType_UPPERCASE_;
J2OBJC_STATIC_FIELD_GETTER(ComFqLibPinyin4jHanyuPinyinCaseType, UPPERCASE_, ComFqLibPinyin4jHanyuPinyinCaseType *)

FOUNDATION_EXPORT ComFqLibPinyin4jHanyuPinyinCaseType *ComFqLibPinyin4jHanyuPinyinCaseType_LOWERCASE_;
J2OBJC_STATIC_FIELD_GETTER(ComFqLibPinyin4jHanyuPinyinCaseType, LOWERCASE_, ComFqLibPinyin4jHanyuPinyinCaseType *)

#endif // _ComFqLibPinyin4jHanyuPinyinCaseType_H_
