//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/HomeData.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityHomeData_H_
#define _ComFqHalcyonEntityHomeData_H_

@class FQJSONObject;

#import "JreEmulation.h"
#include "HalcyonEntity.h"

#define ComFqHalcyonEntityHomeData_READ_STATE_NO 0
#define ComFqHalcyonEntityHomeData_READ_STATE_YES 1
#define ComFqHalcyonEntityHomeData_serialVersionUID 1LL

@interface ComFqHalcyonEntityHomeData : ComFqHalcyonEntityHalcyonEntity {
 @public
  int mFollowUpId_;
  NSString *mImgPath_;
  int mImgID_;
  int mReadFlag_;
  NSString *mFollowUpName_;
  NSString *mPatientName_;
}

- (NSString *)getmFollowUpName;

- (void)setmFollowUpNameWithNSString:(NSString *)mFollowUpName;

- (NSString *)getmPatientName;

- (void)setmPatientNameWithNSString:(NSString *)mPatientName;

- (int)getmFollowUpId;

- (void)setmFollowUpIdWithInt:(int)mFollowUpId;

- (NSString *)getmImgPath;

- (void)setmImgPathWithNSString:(NSString *)mImgPath;

- (int)getmImgID;

- (void)setmImgIDWithInt:(int)mImgID;

- (BOOL)isRead;

- (void)setReadWithInt:(int)readFlag;

- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json;

- (FQJSONObject *)getJson;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityHomeData *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityHomeData_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityHomeData, mImgPath_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityHomeData, mFollowUpName_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityHomeData, mPatientName_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeData, READ_STATE_NO, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeData, READ_STATE_YES, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeData, serialVersionUID, long long int)

#endif // _ComFqHalcyonEntityHomeData_H_
