//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/HomeOneDayData.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityHomeOneDayData_H_
#define _ComFqHalcyonEntityHomeOneDayData_H_

@class ComFqHalcyonEntityHomeData;
@class ComFqHalcyonEntityHomeOneDayData_CurrSateEnum;
@class FQJSONObject;
@class JavaUtilArrayList;
@class JavaUtilCalendar;

#import "JreEmulation.h"
#include "HalcyonEntity.h"
#include "java/lang/Enum.h"

#define ComFqHalcyonEntityHomeOneDayData_serialVersionUID 1LL

@interface ComFqHalcyonEntityHomeOneDayData : ComFqHalcyonEntityHalcyonEntity {
 @public
  JavaUtilArrayList *mHomeDatas_;
  JavaUtilCalendar *mCalendar_;
  ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *mCurrState_;
  int mRecRecongnizedNum_;
}

- (int)getmRecRecongnizedNum;

- (void)setmRecRecongnizedNumWithInt:(int)mRecRecongnizedNum;

- (JavaUtilArrayList *)getDatas;

- (int)getDataCount;

- (ComFqHalcyonEntityHomeData *)getDataWithInt:(int)index;

- (ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *)getCurrentSate;

- (long long int)getTimeMillis;

- (JavaUtilCalendar *)getCalendar;

- (int)getMonth;

- (int)getDayOfWeek;

- (int)getDayOfMonth;

- (BOOL)isHaveUnReadData;

- (void)setCalendarWithLong:(long long int)timeMillis;

- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityHomeOneDayData *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityHomeOneDayData_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityHomeOneDayData, mHomeDatas_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityHomeOneDayData, mCalendar_, JavaUtilCalendar *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityHomeOneDayData, mCurrState_, ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeOneDayData, serialVersionUID, long long int)

typedef enum {
  ComFqHalcyonEntityHomeOneDayData_CurrSate_BEFO = 0,
  ComFqHalcyonEntityHomeOneDayData_CurrSate_CURR = 1,
  ComFqHalcyonEntityHomeOneDayData_CurrSate_AFTER = 2,
} ComFqHalcyonEntityHomeOneDayData_CurrSate;

@interface ComFqHalcyonEntityHomeOneDayData_CurrSateEnum : JavaLangEnum < NSCopying > {
}
+ (IOSObjectArray *)values;
+ (ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *)valueOfWithNSString:(NSString *)name;
- (id)copyWithZone:(NSZone *)zone;

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal;
@end

FOUNDATION_EXPORT BOOL ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_initialized;
J2OBJC_STATIC_INIT(ComFqHalcyonEntityHomeOneDayData_CurrSateEnum)

FOUNDATION_EXPORT ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_values[];

#define ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_BEFO ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_values[ComFqHalcyonEntityHomeOneDayData_CurrSate_BEFO]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeOneDayData_CurrSateEnum, BEFO, ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *)

#define ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_CURR ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_values[ComFqHalcyonEntityHomeOneDayData_CurrSate_CURR]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeOneDayData_CurrSateEnum, CURR, ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *)

#define ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_AFTER ComFqHalcyonEntityHomeOneDayData_CurrSateEnum_values[ComFqHalcyonEntityHomeOneDayData_CurrSate_AFTER]
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityHomeOneDayData_CurrSateEnum, AFTER, ComFqHalcyonEntityHomeOneDayData_CurrSateEnum *)

#endif // _ComFqHalcyonEntityHomeOneDayData_H_
