//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Hospital.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Hospital.java"

#include "Hospital.h"
#include "JSONObject.h"


#line 6
@implementation ComFqHalcyonEntityHospital


#line 12
- (int)getHospitalId {
  
#line 13
  return id__;
}


#line 15
- (void)setHospitalIdWithInt:(int)hospitalId {
  
#line 16
  self->id__ = hospitalId;
}


#line 20
- (void)test {
}


#line 25
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  
#line 26
  [super setAtttributeByjsonWithFQJSONObject:json];
  self->id__ = [((FQJSONObject *) nil_chk(json)) optIntWithNSString:@"id"];
}

- (id)init {
  return [super init];
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityHospital *)other {
  [super copyAllFieldsTo:other];
  other->id__ = id__;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getHospitalId", NULL, "I", 0x1, NULL },
    { "setHospitalIdWithInt:", "setHospitalId", "V", 0x1, NULL },
    { "test", NULL, "V", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_Hospital_", "serialVersionUID", 0x1a, "J", NULL, .constantValue.asLong = ComFqHalcyonEntityHospital_serialVersionUID },
    { "id__", "id", 0x2, "I", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityHospital = { "Hospital", "com.fq.halcyon.entity", NULL, 0x1, 5, methods, 2, fields, 0, NULL};
  return &_ComFqHalcyonEntityHospital;
}

@end
