//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/potocol/HttpClientPotocol.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpPotocolHttpClientPotocol_H_
#define _ComFqHttpPotocolHttpClientPotocol_H_

@class ComFqHttpAsyncParamsWrapper;
@protocol ComFqHttpPotocolHttpRequestPotocol;
@protocol FQHttpResponseHandle;

#import "JreEmulation.h"

#define ComFqHttpPotocolHttpClientPotocol_DEFAULT_TIME_OUT 10

@interface ComFqHttpPotocolHttpClientPotocol : NSObject {
}

+ (ComFqHttpPotocolHttpClientPotocol *)getInstance;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                      withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                     withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                      withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle
                                                              withInt:(int)timeOut;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                     withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle
                                                             withInt:(int)timeOut;

- (NSString *)encodeWithNSString:(NSString *)value;

- (NSString *)decodeWithNSString:(NSString *)value;

- (id)init;

@end

__attribute__((always_inline)) inline void ComFqHttpPotocolHttpClientPotocol_init() {}

J2OBJC_STATIC_FIELD_GETTER(ComFqHttpPotocolHttpClientPotocol, DEFAULT_TIME_OUT, int)

FOUNDATION_EXPORT ComFqHttpPotocolHttpClientPotocol *ComFqHttpPotocolHttpClientPotocol_mInstance_;
J2OBJC_STATIC_FIELD_GETTER(ComFqHttpPotocolHttpClientPotocol, mInstance_, ComFqHttpPotocolHttpClientPotocol *)
J2OBJC_STATIC_FIELD_SETTER(ComFqHttpPotocolHttpClientPotocol, mInstance_, ComFqHttpPotocolHttpClientPotocol *)

#endif // _ComFqHttpPotocolHttpClientPotocol_H_
