//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/potocol/HttpParamPotocol.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpPotocolHttpParamPotocol_H_
#define _ComFqHttpPotocolHttpParamPotocol_H_

@class JavaIoFile;
@class JavaIoInputStream;

#import "JreEmulation.h"

@protocol ComFqHttpPotocolHttpParamPotocol < NSObject, JavaObject >

- (void)putWithNSString:(NSString *)key
           withNSString:(NSString *)value;

- (void)putWithNSString:(NSString *)key
         withJavaIoFile:(JavaIoFile *)file;

- (void)putWithNSString:(NSString *)key
         withJavaIoFile:(JavaIoFile *)file
           withNSString:(NSString *)contentType;

- (void)putWithNSString:(NSString *)key
  withJavaIoInputStream:(JavaIoInputStream *)stream;

- (void)putWithNSString:(NSString *)key
  withJavaIoInputStream:(JavaIoInputStream *)stream
           withNSString:(NSString *)name;

- (void)putWithNSString:(NSString *)key
  withJavaIoInputStream:(JavaIoInputStream *)stream
           withNSString:(NSString *)name
           withNSString:(NSString *)contentType;

- (void)putWithNSString:(NSString *)key
  withJavaIoInputStream:(JavaIoInputStream *)stream
           withNSString:(NSString *)name
           withNSString:(NSString *)contentType
            withBoolean:(BOOL)autoClose;

- (void)putWithNSString:(NSString *)key
                 withId:(id)value;

- (void)putWithNSString:(NSString *)key
                withInt:(int)value;

- (void)putWithNSString:(NSString *)key
               withLong:(long long int)value;

@end

__attribute__((always_inline)) inline void ComFqHttpPotocolHttpParamPotocol_init() {}

#endif // _ComFqHttpPotocolHttpParamPotocol_H_
