//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/potocol/HttpRequestPotocol.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpPotocolHttpRequestPotocol_H_
#define _ComFqHttpPotocolHttpRequestPotocol_H_

#import "JreEmulation.h"

@protocol ComFqHttpPotocolHttpRequestPotocol < NSObject, JavaObject >

- (void)cancel;

@end

__attribute__((always_inline)) inline void ComFqHttpPotocolHttpRequestPotocol_init() {}

#endif // _ComFqHttpPotocolHttpRequestPotocol_H_
