//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/callback/ICallback.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqLibCallbackICallback_H_
#define _ComFqLibCallbackICallback_H_

#import "JreEmulation.h"

@protocol ComFqLibCallbackICallback < NSObject, JavaObject >

- (void)doCallbackWithId:(id)obj;

@end

__attribute__((always_inline)) inline void ComFqLibCallbackICallback_init() {}

#endif // _ComFqLibCallbackICallback_H_
