//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/async/uploadloop/LoopCellHandle.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpAsyncUploadloopLoopCellHandle_H_
#define _ComFqHttpAsyncUploadloopLoopCellHandle_H_

@class ComFqHalcyonEntityPhoto;
@class ComFqHttpAsyncUploadloopFQLoopQueue;
@class ComFqHttpAsyncUploadloopLoopCell;
@class JavaIoFile;
@class JavaLangThrowable;
@class JavaUtilArrayList;
@protocol ComFqHttpPotocolHttpRequestPotocol;

#import "JreEmulation.h"
#include "HalcyonHttpResponseHandle.h"
#include "ParamsWrapper.h"
#include "onHandlerCompleteListener.h"

@interface ComFqHttpAsyncUploadloopLoopCellHandle : NSObject < ComFqHttpAsyncUploadlooponHandlerCompleteListener > {
 @public
  ComFqHttpAsyncUploadloopFQLoopQueue *mQueue_;
  float mProcess_;
  BOOL isHanlding_;
  id<ComFqHttpAsyncUploadlooponHandlerCompleteListener> completeListener_;
  id<ComFqHttpAsyncParamsWrapper_FQProcessInterface> processListener_;
  id<ComFqHttpPotocolHttpRequestPotocol> mCurrentRequestHandle_;
  ComFqHttpAsyncUploadloopLoopCell *cell_;
  JavaIoFile *path_;
  ComFqHalcyonEntityPhoto *pathPhoto_;
  ComFqHalcyonEntityPhoto *photo_;
  JavaUtilArrayList *subHandles_;
  ComFqHttpAsyncUploadloopLoopCellHandle *parent_;
  BOOL mIsPause_;
  BOOL mIsFinished_;
  int mRecordItemId_;
}

- (void)setProcessListemerWithComFqHttpAsyncParamsWrapper_FQProcessInterface:(id<ComFqHttpAsyncParamsWrapper_FQProcessInterface>)process;

- (void)resume;

- (void)cancle;

- (void)remove;

- (id)initWithComFqHttpAsyncUploadloopLoopCell:(ComFqHttpAsyncUploadloopLoopCell *)cell;

- (void)setQueueWithComFqHttpAsyncUploadloopFQLoopQueue:(ComFqHttpAsyncUploadloopFQLoopQueue *)mQueue;

- (void)onHandle;

- (id<ComFqHttpAsyncUploadlooponHandlerCompleteListener>)getCompleteListener;

- (void)setOnCompleteListenerWithComFqHttpAsyncUploadlooponHandlerCompleteListener:(id<ComFqHttpAsyncUploadlooponHandlerCompleteListener>)completeListener;

- (void)onHandlerCompleteWithComFqHttpAsyncUploadloopLoopCellHandle:(ComFqHttpAsyncUploadloopLoopCellHandle *)cellHanle
                                                            withInt:(int)type
                                                             withId:(id)results;

- (double)getProcess;

- (void)copyAllFieldsTo:(ComFqHttpAsyncUploadloopLoopCellHandle *)other;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncUploadloopLoopCellHandle_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, mQueue_, ComFqHttpAsyncUploadloopFQLoopQueue *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, completeListener_, id<ComFqHttpAsyncUploadlooponHandlerCompleteListener>)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, processListener_, id<ComFqHttpAsyncParamsWrapper_FQProcessInterface>)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, mCurrentRequestHandle_, id<ComFqHttpPotocolHttpRequestPotocol>)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, cell_, ComFqHttpAsyncUploadloopLoopCell *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, path_, JavaIoFile *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, pathPhoto_, ComFqHalcyonEntityPhoto *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, photo_, ComFqHalcyonEntityPhoto *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, subHandles_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle, parent_, ComFqHttpAsyncUploadloopLoopCellHandle *)

@interface ComFqHttpAsyncUploadloopLoopCellHandle_$1 : HalcyonHttpResponseHandle {
 @public
  ComFqHttpAsyncUploadloopLoopCellHandle *this$0_;
  JavaIoFile *val$filePath_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHttpAsyncUploadloopLoopCellHandle:(ComFqHttpAsyncUploadloopLoopCellHandle *)outer$
                                      withJavaIoFile:(JavaIoFile *)capture$0;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncUploadloopLoopCellHandle_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle_$1, this$0_, ComFqHttpAsyncUploadloopLoopCellHandle *)
J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle_$1, val$filePath_, JavaIoFile *)

@interface ComFqHttpAsyncUploadloopLoopCellHandle_$2 : NSObject < ComFqHttpAsyncParamsWrapper_FQProcessInterface > {
 @public
  ComFqHttpAsyncUploadloopLoopCellHandle *this$0_;
  long long int val$currnetFileSize_;
}

- (void)setProcessWithFloat:(float)process;

- (id)initWithComFqHttpAsyncUploadloopLoopCellHandle:(ComFqHttpAsyncUploadloopLoopCellHandle *)outer$
                                            withLong:(long long int)capture$0;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncUploadloopLoopCellHandle_$2_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle_$2, this$0_, ComFqHttpAsyncUploadloopLoopCellHandle *)

@interface ComFqHttpAsyncUploadloopLoopCellHandle_$3 : HalcyonHttpResponseHandle {
 @public
  ComFqHttpAsyncUploadloopLoopCellHandle *this$0_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHttpAsyncUploadloopLoopCellHandle:(ComFqHttpAsyncUploadloopLoopCellHandle *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncUploadloopLoopCellHandle_$3_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncUploadloopLoopCellHandle_$3, this$0_, ComFqHttpAsyncUploadloopLoopCellHandle *)

#endif // _ComFqHttpAsyncUploadloopLoopCellHandle_H_
