//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/ModifyRecordNameLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2ModifyRecordNameLogic_H_
#define _ComFqHalcyonLogic2ModifyRecordNameLogic_H_

@class JavaLangThrowable;
@protocol ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack;

#import "JreEmulation.h"
#include "HalcyonHttpResponseHandle.h"

@interface ComFqHalcyonLogic2ModifyRecordNameLogic : NSObject {
 @public
  id<ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack> onCallBack_;
}

- (id)initWithComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack:(id<ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack>)onCallBack;

- (void)modifyNameWithInt:(int)patientId
             withNSString:(NSString *)patientName;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2ModifyRecordNameLogic *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2ModifyRecordNameLogic_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2ModifyRecordNameLogic, onCallBack_, id<ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack>)

@interface ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyNameHandler : HalcyonHttpResponseHandle {
 @public
  ComFqHalcyonLogic2ModifyRecordNameLogic *this$0_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2ModifyRecordNameLogic:(ComFqHalcyonLogic2ModifyRecordNameLogic *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyNameHandler_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyNameHandler, this$0_, ComFqHalcyonLogic2ModifyRecordNameLogic *)

@protocol ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack < NSObject, JavaObject >

- (void)modifyNameSuccessWithInt:(int)code
                    withNSString:(NSString *)msg;

- (void)modifyNameErrorWithInt:(int)code
                  withNSString:(NSString *)msg;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2ModifyRecordNameLogic_ModifyRecordNameCallBack_init() {}

#endif // _ComFqHalcyonLogic2ModifyRecordNameLogic_H_
