//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uimodels/OneType.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uimodels/OneType.java"

#include "JSONArray.h"
#include "JSONException.h"
#include "JSONObject.h"
#include "OneCopy.h"
#include "OneType.h"
#include "java/lang/Exception.h"
#include "java/util/ArrayList.h"
#include "java/util/UUID.h"

@implementation ComFqHalcyonUimodelsOneType


#line 26
- (id)initWithInt:(int)type {
  if (self = [super init]) {
    type_ =
#line 22
    0;
    copies_ =
#line 24
    [[JavaUtilArrayList alloc] init];
    uuid_ =
#line 34
    [((JavaUtilUUID *) nil_chk([JavaUtilUUID randomUUID])) description];
    
#line 27
    self->type_ = type;
  }
  return self;
}


#line 30
- (void)AddOneCopyWithComFqHalcyonUimodelsOneCopy:(ComFqHalcyonUimodelsOneCopy *)oneCopy {
  
#line 31
  [((JavaUtilArrayList *) nil_chk(copies_)) addWithId:oneCopy];
}

- (void)addOneCopysWithJavaUtilArrayList:(JavaUtilArrayList *)copies {
  
#line 37
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(copies)) size]; i++) {
    ComFqHalcyonUimodelsOneCopy *copy_ = [copies getWithInt:i];
    if ([((JavaUtilArrayList *) nil_chk([((ComFqHalcyonUimodelsOneCopy *) nil_chk(copy_)) getPhotos])) size] > 0) {
      [((JavaUtilArrayList *) nil_chk(self->copies_)) addWithId:copy_];
    }
  }
}


#line 45
- (int)getType {
  
#line 46
  return type_;
}


#line 49
- (int)getUITypeIndex {
  
#line 50
  return type_;
}


#line 53
- (void)setUITypeIndexWithInt:(int)typeIndex {
  
#line 54
  type_ = typeIndex;
}


#line 57
- (ComFqHalcyonUimodelsOneCopy *)getCopyByIdWithInt:(int)index {
  
#line 58
  return [((JavaUtilArrayList *) nil_chk(copies_)) getWithInt:index];
}


#line 61
- (JavaUtilArrayList *)getAllCopies {
  
#line 62
  return copies_;
}


#line 65
- (ComFqHalcyonUimodelsOneCopy *)lastCopy {
  
#line 66
  if ([((JavaUtilArrayList *) nil_chk(copies_)) size] > 0) {
    return [copies_ getWithInt:[copies_ size] - 1];
  }
  else {
    
#line 69
    return nil;
  }
}


#line 81
- (FQJSONObject *)getJsonObj {
  
#line 82
  FQJSONObject *json = [[FQJSONObject alloc] init];
  FQJSONArray *jsonArray = [[FQJSONArray alloc] init];
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(copies_)) size]; i++) {
    ComFqHalcyonUimodelsOneCopy *copy_ = [copies_ getWithInt:i];
    (void) [jsonArray putWithId:[((ComFqHalcyonUimodelsOneCopy *) nil_chk(copy_)) getJsonObj]];
  }
  @try {
    (void) [json putWithNSString:@"uiTypeIndex" withInt:type_];
    (void) [json putWithNSString:@"copies" withId:jsonArray];
  }
  @catch (
#line 91
  FQJSONException *e) {
    [((FQJSONException *) nil_chk(e)) printStackTrace];
  }
  return json;
}


#line 97
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  
#line 98
  @try {
    type_ = [((FQJSONObject *) nil_chk(json)) getIntWithNSString:@"uiTypeIndex"];
    FQJSONArray *array = [json optJSONArrayWithNSString:@"copies"];
    if ([((FQJSONArray *) nil_chk(array)) length] < 1) return;
    for (int i = 0; i < [array length]; i++) {
      ComFqHalcyonUimodelsOneCopy *copy_ = [[ComFqHalcyonUimodelsOneCopy alloc] initWithInt:type_];
      [copy_ setAtttributeByjsonWithFQJSONObject:[array getJSONObjectWithInt:i]];
      [((JavaUtilArrayList *) nil_chk(copies_)) addWithId:copy_];
    }
  }
  @catch (
#line 107
  JavaLangException *e) {
    [((JavaLangException *) nil_chk(e)) printStackTrace];
    return;
  }
}


#line 113
- (JavaUtilArrayList *)getAllPhotos {
  
#line 114
  JavaUtilArrayList *photos = [[JavaUtilArrayList alloc] init];
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(copies_)) size]; i++) {
    ComFqHalcyonUimodelsOneCopy *copy_ = [copies_ getWithInt:i];
    [photos addAllWithJavaUtilCollection:[((ComFqHalcyonUimodelsOneCopy *) nil_chk(copy_)) getPhotos]];
  }
  return photos;
}


#line 122
- (BOOL)isHavaPhotoByIdWithInt:(int)id_ {
  
#line 123
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(copies_)) size]; i++) {
    if ([((ComFqHalcyonUimodelsOneCopy *) nil_chk([copies_ getWithInt:i])) isHavePhotoByIdWithInt:id_]) {
      return YES;
    }
  }
  return NO;
}


#line 131
- (BOOL)isHavaPhotoByUrlWithNSString:(NSString *)url {
  
#line 132
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(copies_)) size]; i++) {
    if ([((ComFqHalcyonUimodelsOneCopy *) nil_chk([copies_ getWithInt:i])) isHavePhotoByUrlWithNSString:url]) {
      return YES;
    }
  }
  return NO;
}


#line 140
- (int)getPhotoCounter {
  
#line 141
  int cnt = 0;
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(copies_)) size]; i++) {
    cnt += [((JavaUtilArrayList *) nil_chk([((ComFqHalcyonUimodelsOneCopy *) nil_chk([copies_ getWithInt:i])) getPhotos])) size];
  }
  return cnt;
}

- (void)copyAllFieldsTo:(ComFqHalcyonUimodelsOneType *)other {
  [super copyAllFieldsTo:other];
  other->copies_ = copies_;
  other->type_ = type_;
  other->uuid_ = uuid_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithInt:", "OneType", NULL, 0x1, NULL },
    { "AddOneCopyWithComFqHalcyonUimodelsOneCopy:", "AddOneCopy", "V", 0x1, NULL },
    { "addOneCopysWithJavaUtilArrayList:", "addOneCopys", "V", 0x1, NULL },
    { "getType", NULL, "I", 0x1, NULL },
    { "getUITypeIndex", NULL, "I", 0x1, NULL },
    { "setUITypeIndexWithInt:", "setUITypeIndex", "V", 0x1, NULL },
    { "getCopyByIdWithInt:", "getCopyById", "Lcom.fq.halcyon.uimodels.OneCopy;", 0x1, NULL },
    { "getAllCopies", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "lastCopy", NULL, "Lcom.fq.halcyon.uimodels.OneCopy;", 0x1, NULL },
    { "getJsonObj", NULL, "Lcom.fq.lib.json.JSONObject;", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "getAllPhotos", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "isHavaPhotoByIdWithInt:", "isHavaPhotoById", "Z", 0x1, NULL },
    { "isHavaPhotoByUrlWithNSString:", "isHavaPhotoByUrl", "Z", 0x1, NULL },
    { "getPhotoCounter", NULL, "I", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_", NULL, 0x1a, "J", NULL, .constantValue.asLong = ComFqHalcyonUimodelsOneType_serialVersionUID },
    { "type_", NULL, 0x2, "I", NULL,  },
    { "copies_", NULL, 0x0, "Ljava.util.ArrayList;", NULL,  },
    { "uuid_", NULL, 0x11, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonUimodelsOneType = { "OneType", "com.fq.halcyon.uimodels", NULL, 0x1, 15, methods, 4, fields, 0, NULL};
  return &_ComFqHalcyonUimodelsOneType;
}

@end
