//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/OperateFollowUpTempleLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2OperateFollowUpTempleLogic_H_
#define _ComFqHalcyonLogic2OperateFollowUpTempleLogic_H_

@class ComFqHalcyonEntityFollowUpTemple;
@class ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicHandle;
@class JavaLangThrowable;
@protocol ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicInterface;

#import "JreEmulation.h"
#include "FQHttpResponseInterface.h"
#include "HalcyonHttpResponseHandle.h"

@interface ComFqHalcyonLogic2OperateFollowUpTempleLogic : NSObject {
 @public
  ComFqHalcyonEntityFollowUpTemple *mFollowUpTemple_;
  __weak id<ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicInterface> mInterface_;
  ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicHandle *mHandle_;
}

- (id)initWithComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicInterface:(id<ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicInterface>)mIn
                                                          withComFqHalcyonEntityFollowUpTemple:(ComFqHalcyonEntityFollowUpTemple *)followUpTemple;

- (void)CreateFollowUPTemple;

- (void)ModifyFollowUpTemple;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2OperateFollowUpTempleLogic *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2OperateFollowUpTempleLogic_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2OperateFollowUpTempleLogic, mFollowUpTemple_, ComFqHalcyonEntityFollowUpTemple *)
J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2OperateFollowUpTempleLogic, mHandle_, ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicHandle *)

@protocol ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicInterface < ComFqHttpPotocolFQHttpResponseInterface, NSObject, JavaObject >
- (void)onDataErrorWithInt:(int)code
              withNSString:(NSString *)msg;

- (void)onDataReturn;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicInterface_init() {}

@interface ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicHandle : HalcyonHttpResponseHandle {
 @public
  ComFqHalcyonLogic2OperateFollowUpTempleLogic *this$0_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2OperateFollowUpTempleLogic:(ComFqHalcyonLogic2OperateFollowUpTempleLogic *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicHandle_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2OperateFollowUpTempleLogic_OperateFollowUpTempleLogicHandle, this$0_, ComFqHalcyonLogic2OperateFollowUpTempleLogic *)

#endif // _ComFqHalcyonLogic2OperateFollowUpTempleLogic_H_
