//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/async/ParamsWrapper.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHttpAsyncParamsWrapper_H_
#define _ComFqHttpAsyncParamsWrapper_H_

@protocol ComFqHttpAsyncParamsWrapper_FQProcessInterface;

#import "JreEmulation.h"
#include "RequestParams.h"

#define ComFqHttpAsyncParamsWrapper_serialVersionUID 1LL

@interface ComFqHttpAsyncParamsWrapper : ComLoopjAndroidHttpRequestParams {
 @public
  id<ComFqHttpAsyncParamsWrapper_FQProcessInterface> upLoadProcess_;
  int timeOutTime_;
}

- (void)setTimeoutTimeWithInt:(int)timeOut;

- (int)getTimeoutTime;

- (id<ComFqHttpAsyncParamsWrapper_FQProcessInterface>)getUpLoadProcess;

- (void)setUpLoadProcessWithComFqHttpAsyncParamsWrapper_FQProcessInterface:(id<ComFqHttpAsyncParamsWrapper_FQProcessInterface>)upLoadProcess;

- (NSString *)getStringParams;

- (BOOL)isJsonParams;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHttpAsyncParamsWrapper *)other;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncParamsWrapper_init() {}

J2OBJC_FIELD_SETTER(ComFqHttpAsyncParamsWrapper, upLoadProcess_, id<ComFqHttpAsyncParamsWrapper_FQProcessInterface>)

J2OBJC_STATIC_FIELD_GETTER(ComFqHttpAsyncParamsWrapper, serialVersionUID, long long int)

@protocol ComFqHttpAsyncParamsWrapper_FQProcessInterface < NSObject, JavaObject >

- (void)setProcessWithFloat:(float)process;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncParamsWrapper_FQProcessInterface_init() {}

#endif // _ComFqHttpAsyncParamsWrapper_H_
