//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/PatientFriend.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/PatientFriend.java"

#include "JSONObject.h"
#include "PatientFriend.h"


#line 10
@implementation ComFqHalcyonEntityPatientFriend


#line 26
- (NSString *)getPatientName {
  
#line 27
  return patientName_;
}


#line 29
- (void)setPatientNameWithNSString:(NSString *)patientName {
  
#line 30
  self->patientName_ = patientName;
}


#line 32
- (NSString *)getHeadPath {
  
#line 33
  return headPath_;
}


#line 35
- (void)setHeadPathWithNSString:(NSString *)headPath {
  
#line 36
  self->headPath_ = headPath;
}


#line 39
- (NSString *)getPatientFriendGender {
  
#line 40
  return patientFriendGender_;
}


#line 42
- (void)setPatientFriendGenderWithNSString:(NSString *)patientFriendGender {
  
#line 43
  self->patientFriendGender_ = patientFriendGender;
}


#line 46
- (NSString *)getName {
  
#line 47
  return name_PatientFriend_;
}


#line 49
- (void)setNameWithNSString:(NSString *)name {
  
#line 50
  self->name_PatientFriend_ = name;
}


#line 52
- (NSString *)getDescription {
  
#line 53
  return description_PatientFriend_;
}


#line 55
- (void)setDescriptionWithNSString:(NSString *)description_ {
  
#line 56
  self->description_PatientFriend_ = description_;
}


#line 58
- (int)getPatientId {
  
#line 59
  return patientId_;
}


#line 61
- (void)setPatientIdWithInt:(int)patientId {
  
#line 62
  self->patientId_ = patientId;
}


#line 66
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  [super setAtttributeByjsonWithFQJSONObject:json];
  self->name_PatientFriend_ = [((FQJSONObject *) nil_chk(json)) optStringWithNSString:@"name"];
  self->patientFriendGender_ = [json optStringWithNSString:@"gender"];
  self->description_PatientFriend_ = [json optStringWithNSString:@"description"];
  self->patientId_ = [json optIntWithNSString:@"patient_id"];
  self->headPath_ = [json optStringWithNSString:@"image_path"];
  self->patientName_ = [json optStringWithNSString:@"patient_name"];
}

- (id)init {
  return [super init];
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityPatientFriend *)other {
  [super copyAllFieldsTo:other];
  other->description_PatientFriend_ = description_PatientFriend_;
  other->headPath_ = headPath_;
  other->name_PatientFriend_ = name_PatientFriend_;
  other->patientFriendGender_ = patientFriendGender_;
  other->patientId_ = patientId_;
  other->patientName_ = patientName_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getPatientName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setPatientNameWithNSString:", "setPatientName", "V", 0x1, NULL },
    { "getHeadPath", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setHeadPathWithNSString:", "setHeadPath", "V", 0x1, NULL },
    { "getPatientFriendGender", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setPatientFriendGenderWithNSString:", "setPatientFriendGender", "V", 0x1, NULL },
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setNameWithNSString:", "setName", "V", 0x1, NULL },
    { "getDescription", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setDescriptionWithNSString:", "setDescription", "V", 0x1, NULL },
    { "getPatientId", NULL, "I", 0x1, NULL },
    { "setPatientIdWithInt:", "setPatientId", "V", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_PatientFriend_", "serialVersionUID", 0x1a, "J", NULL, .constantValue.asLong = ComFqHalcyonEntityPatientFriend_serialVersionUID },
    { "headPath_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "patientFriendGender_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
    { "name_PatientFriend_", "name", 0x2, "Ljava.lang.String;", NULL,  },
    { "description_PatientFriend_", "description", 0x2, "Ljava.lang.String;", NULL,  },
    { "patientId_", NULL, 0x2, "I", NULL,  },
    { "patientName_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityPatientFriend = { "PatientFriend", "com.fq.halcyon.entity", NULL, 0x1, 14, methods, 7, fields, 0, NULL};
  return &_ComFqHalcyonEntityPatientFriend;
}

@end
