//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/Patient.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityPatient_H_
#define _ComFqHalcyonEntityPatient_H_

@class FQJSONObject;

#import "JreEmulation.h"
#include "HalcyonEntity.h"

#define ComFqHalcyonEntityPatient_serialVersionUID 1LL

@interface ComFqHalcyonEntityPatient : ComFqHalcyonEntityHalcyonEntity {
 @public
  int medicalId_;
  NSString *medicalName_;
  int medicalFromType_;
  NSString *medicalFrom_;
  NSString *createTime_;
  int recordCount_;
  int notRecCount_;
  int fromUserType_;
}

- (int)getMedicalId;

- (void)setMedicalIdWithInt:(int)medicalId;

- (NSString *)getMedicalName;

- (void)setMedicalNameWithNSString:(NSString *)medicalName;

- (int)getMedicalFromType;

- (void)setMedicalFromTypeWithInt:(int)medicalFromType;

- (NSString *)getMedicalFrom;

- (void)setMedicalFromWithNSString:(NSString *)medicalFrom;

- (NSString *)getCreateTime;

- (void)setCreateTimeWithNSString:(NSString *)createTime;

- (int)getRecordCount;

- (void)setRecordCountWithInt:(int)recordCount;

- (int)getNotRecCount;

- (void)setNotRecCountWithInt:(int)notRecCount;

- (int)getFromUserType;

- (void)setFromUserTypeWithInt:(int)fromUserType;

- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json;

- (void)test;

- (id)init;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityPatient *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityPatient_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityPatient, medicalName_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityPatient, medicalFrom_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityPatient, createTime_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityPatient, serialVersionUID, long long int)

#endif // _ComFqHalcyonEntityPatient_H_
