//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uilogic/PersonInfoUILogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uilogic/PersonInfoUILogic.java"

#include "CertificationStatus.h"
#include "Constants.h"
#include "PersonInfoUILogic.h"
#include "User.h"


#line 6
@implementation ComFqHalcyonUilogicPersonInfoUILogic


#line 11
+ (BOOL)checkUserInfo {
  
#line 13
  NSString *name = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getName];
  NSString *hospital = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getHospital];
  NSString *department = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getDepartment];
  int gender = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getGender];
  NSString *description_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getDescription];
  NSString *headPicPath = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getHeadPicPath];
  
#line 20
  if (nil == name || [@"" isEqual:name]) {
    return NO;
  }
  else
#line 22
  if (nil == hospital || [@"" isEqual:hospital]) {
    return NO;
  }
  else
#line 24
  if (nil == department || [@"" isEqual:department]) {
    return NO;
  }
  else
#line 26
  if (gender != 1 && gender != 2) {
    return NO;
  }
  else
#line 28
  if (nil == description_ || [@"" isEqual:description_]) {
    return NO;
  }
  else
#line 30
  if (nil == headPicPath || [@"" isEqual:headPicPath]) {
    return NO;
  }
  else
#line 32
  if (![((ComFqHalcyonEntityCertificationStatus *) nil_chk([ComFqHalcyonEntityCertificationStatus getInstance])) isHaveAuth]) {
    
#line 34
    return NO;
  }
  else {
    
#line 36
    return YES;
  }
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "checkUserInfo", NULL, "Z", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonUilogicPersonInfoUILogic = { "PersonInfoUILogic", "com.fq.halcyon.uilogic", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonUilogicPersonInfoUILogic;
}

@end
