//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/pinyin4j/PinyinRomanizationTranslator.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqLibPinyin4jPinyinRomanizationTranslator_H_
#define _ComFqLibPinyin4jPinyinRomanizationTranslator_H_

#import "JreEmulation.h"

@interface ComFqLibPinyin4jPinyinRomanizationTranslator : NSObject {
}

- (id)init;

@end

__attribute__((always_inline)) inline void ComFqLibPinyin4jPinyinRomanizationTranslator_init() {}

#endif // _ComFqLibPinyin4jPinyinRomanizationTranslator_H_
