//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/pinyin4j/PinyinRomanizationResource.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/pinyin4j/PinyinRomanizationResource.java"

#include "PinyinRomanizationResource.h"


#line 35
@implementation ComFqLibPinyin4jPinyinRomanizationResource

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _ComFqLibPinyin4jPinyinRomanizationResource = { "PinyinRomanizationResource", "com.fq.lib.pinyin4j", NULL, 0x0, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqLibPinyin4jPinyinRomanizationResource;
}

@end
