//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/RecordType.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/RecordType.java"

#include "JSONArray.h"
#include "JSONObject.h"
#include "RecordItemSamp.h"
#include "RecordType.h"
#include "java/util/ArrayList.h"

@implementation ComFqHalcyonEntityRecordType


#line 19
- (int)getRecordType {
  
#line 20
  return recordType_;
}


#line 23
- (void)setRecordTypeWithInt:(int)recordType {
  
#line 24
  self->recordType_ = recordType;
}


#line 27
- (JavaUtilArrayList *)getItemList {
  
#line 28
  return mItemList_;
}


#line 31
- (void)setItemListWithJavaUtilArrayList:(JavaUtilArrayList *)mItemList {
  
#line 32
  self->mItemList_ = mItemList;
}


#line 35
- (ComFqHalcyonEntityRecordItemSamp *)getItemWithInt:(int)position {
  
#line 36
  return (ComFqHalcyonEntityRecordItemSamp *) check_class_cast([((JavaUtilArrayList *) nil_chk(mItemList_)) getWithInt:position], [ComFqHalcyonEntityRecordItemSamp class]);
}


#line 39
- (void)addItemWithComFqHalcyonEntityRecordItemSamp:(ComFqHalcyonEntityRecordItemSamp *)item {
  
#line 40
  [((JavaUtilArrayList *) nil_chk(mItemList_)) addWithId:item];
}


#line 43
- (void)addItemsWithJavaUtilArrayList:(JavaUtilArrayList *)items {
  
#line 44
  [((JavaUtilArrayList *) nil_chk(mItemList_)) addAllWithJavaUtilCollection:items];
}


#line 47
- (void)addItemsWithInt:(int)index
  withJavaUtilArrayList:(JavaUtilArrayList *)items {
  
#line 48
  [((JavaUtilArrayList *) nil_chk(mItemList_)) addAllWithInt:index withJavaUtilCollection:items];
}


#line 52
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  
#line 53
  self->recordType_ = [((FQJSONObject *) nil_chk(json)) optIntWithNSString:@"record_type"];
  
#line 55
  [((JavaUtilArrayList *) nil_chk(mItemList_)) clear];
  FQJSONArray *jsonArr = [json optJSONArrayWithNSString:@"record_items"];
  int count = [((FQJSONArray *) nil_chk(jsonArr)) length];
  for (int i = 0; i < count; i++) {
    FQJSONObject *jsonObj = [jsonArr optJSONObjectWithInt:i];
    ComFqHalcyonEntityRecordItemSamp *item = [[ComFqHalcyonEntityRecordItemSamp alloc] init];
    [item setReocrdTypeWithInt:recordType_];
    [item setAtttributeByjsonWithFQJSONObject:jsonObj];
    [mItemList_ addWithId:item];
  }
}

- (id)init {
  if (self = [super init]) {
    mItemList_ =
#line 17
    [[JavaUtilArrayList alloc] init];
  }
  return self;
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityRecordType *)other {
  [super copyAllFieldsTo:other];
  other->mItemList_ = mItemList_;
  other->recordType_ = recordType_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getRecordType", NULL, "I", 0x1, NULL },
    { "setRecordTypeWithInt:", "setRecordType", "V", 0x1, NULL },
    { "getItemList", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "setItemListWithJavaUtilArrayList:", "setItemList", "V", 0x1, NULL },
    { "getItemWithInt:", "getItem", "Lcom.fq.halcyon.entity.RecordItemSamp;", 0x1, NULL },
    { "addItemWithComFqHalcyonEntityRecordItemSamp:", "addItem", "V", 0x1, NULL },
    { "addItemsWithJavaUtilArrayList:", "addItems", "V", 0x1, NULL },
    { "addItemsWithInt:withJavaUtilArrayList:", "addItems", "V", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "serialVersionUID_RecordType_", "serialVersionUID", 0x1a, "J", NULL, .constantValue.asLong = ComFqHalcyonEntityRecordType_serialVersionUID },
    { "recordType_", NULL, 0x2, "I", NULL,  },
    { "mItemList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityRecordType = { "RecordType", "com.fq.halcyon.entity", NULL, 0x1, 10, methods, 3, fields, 0, NULL};
  return &_ComFqHalcyonEntityRecordType;
}

@end
