//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/RecordInfo.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityRecordInfo_H_
#define _ComFqHalcyonEntityRecordInfo_H_

#import "JreEmulation.h"

@interface ComFqHalcyonEntityRecordInfo : NSObject {
 @public
  NSString *key_;
  NSString *info_;
}

- (id)initWithNSString:(NSString *)key
          withNSString:(NSString *)info;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityRecordInfo *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityRecordInfo_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityRecordInfo, key_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityRecordInfo, info_, NSString *)

#endif // _ComFqHalcyonEntityRecordInfo_H_
