//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/record/RecordConstants.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/record/RecordConstants.java"

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "RecordConstants.h"
#include "RecordItem.h"
#include "RecordItemSamp.h"

BOOL ComFqLibRecordRecordConstants_initialized = NO;


#line 6
@implementation ComFqLibRecordRecordConstants

IOSObjectArray * ComFqLibRecordRecordConstants_TYTE_NAME_;
IOSObjectArray * ComFqLibRecordRecordConstants_TYTE_TITLE_;
IOSIntArray * ComFqLibRecordRecordConstants_TYPES_;
IOSIntArray * ComFqLibRecordRecordConstants_ZHUYUAN_IDS_;
IOSIntArray * ComFqLibRecordRecordConstants_MENZEHN_IDS_;
IOSIntArray * ComFqLibRecordRecordConstants_CHECK_ITEMS_;
IOSObjectArray * ComFqLibRecordRecordConstants_TYPE_ABSTRACT_;


#line 151
+ (NSString *)getTypeNameByRecordTypeWithInt:(int)recordType {
  
#line 152
  return IOSObjectArray_Get(nil_chk(ComFqLibRecordRecordConstants_TYTE_NAME_), recordType);
}


#line 155
+ (NSString *)getTypeTitleByRecordTypeWithInt:(int)recordType {
  
#line 156
  return IOSObjectArray_Get(nil_chk(ComFqLibRecordRecordConstants_TYTE_TITLE_), recordType);
}


#line 159
+ (int)getRecordTypeByUIIndexWithInt:(int)uiType {
  
#line 160
  return IOSIntArray_Get(nil_chk(ComFqLibRecordRecordConstants_TYPES_), uiType);
}


#line 167
+ (IOSIntArray *)getTypesByRecordTypeWithInt:(int)type {
  
#line 168
  switch (type) {
    case ComFqLibRecordRecordConstants_RECORD_TYPE_DOORCASE:
    return ComFqLibRecordRecordConstants_MENZEHN_IDS_;
    case ComFqLibRecordRecordConstants_RECORD_TYPE_ADMISSION:
    default:
    return ComFqLibRecordRecordConstants_ZHUYUAN_IDS_;
  }
}


#line 177
+ (IOSIntArray *)getCheckItemIds {
  
#line 178
  return ComFqLibRecordRecordConstants_CHECK_ITEMS_;
}


#line 181
+ (NSString *)getAbstractByTypeWithInt:(int)type {
  
#line 182
  return IOSObjectArray_Get(nil_chk(ComFqLibRecordRecordConstants_TYPE_ABSTRACT_), type);
}


#line 186
+ (int)getBigTypeWithComFqHalcyonEntityRecordItem:(ComFqHalcyonEntityRecordItem *)item {
  int type = [((ComFqHalcyonEntityRecordItem *) nil_chk(item)) getRecordType];
  
#line 190
  if (type >= ComFqLibRecordRecordConstants_TYPE_CT &&
#line 191
  type <= ComFqLibRecordRecordConstants_TYPE_CHAOSHENG) {
    type = ComFqLibRecordRecordConstants_TYPE_MEDICAL_IMAGING;
  }
  return type;
}


#line 197
+ (int)getBigTypeWithComFqHalcyonEntityRecordItemSamp:(ComFqHalcyonEntityRecordItemSamp *)samp {
  int type = [((ComFqHalcyonEntityRecordItemSamp *) nil_chk(samp)) getRecordType];
  
#line 201
  if (type >= ComFqLibRecordRecordConstants_TYPE_CT &&
#line 202
  type <= ComFqLibRecordRecordConstants_TYPE_CHAOSHENG) {
    type = ComFqLibRecordRecordConstants_TYPE_MEDICAL_IMAGING;
  }
  return type;
}

- (id)init {
  return [super init];
}

+ (void)initialize {
  if (self == [ComFqLibRecordRecordConstants class]) {
    ComFqLibRecordRecordConstants_TYTE_NAME_ = [IOSObjectArray arrayWithObjects:(id[]){
#line 71
      @"", @"\u5165\u9662\u8bb0\u5f55", @"\u5316\u9a8c\u5355", @"\u624b\u672f\u8bb0\u5f55", @"\u68c0\u67e5", @"\u51fa\u9662\u8bb0\u5f55", @"\u95e8\u8bca\u8bb0\u5f55", @"", @"", @"\u5176\u4ed6", @"\u6cbb\u7597\u65b9\u6848", @"CT", @"\u5fc3\u7535\u56fe", @"\u8d85\u58f0" } count:14 type:[IOSClass classWithClass:[NSString class]]];
      ComFqLibRecordRecordConstants_TYTE_TITLE_ = [IOSObjectArray arrayWithObjects:(id[]){
#line 73
        @"", @"\u5165\u9662", @"\u5316\u9a8c", @"\u624b\u672f", @"\u68c0\u67e5", @"\u51fa\u9662", @"\u95e8\u8bca\u8bb0\u5f55", @"", @"", @"\u5176\u4ed6", @"\u6cbb\u7597\u65b9\u6848", @"CT", @"\u5fc3\u7535\u56fe", @"\u8d85\u58f0" } count:14 type:[IOSClass classWithClass:[NSString class]]];
        ComFqLibRecordRecordConstants_TYPES_ = [IOSIntArray arrayWithInts:(int[]){
#line 80
          ComFqLibRecordRecordConstants_TYPE_ADMISSION, ComFqLibRecordRecordConstants_TYPE_EXAMINATION, ComFqLibRecordRecordConstants_TYPE_SUGERY, ComFqLibRecordRecordConstants_TYPE_MEDICAL_IMAGING, ComFqLibRecordRecordConstants_TYPE_DISCHARGE,
#line 81
          ComFqLibRecordRecordConstants_TYPE_OUTPATIENTS, ComFqLibRecordRecordConstants_TYPE_OTHERS, ComFqLibRecordRecordConstants_TYPE_DOORCASE } count:8];
          ComFqLibRecordRecordConstants_ZHUYUAN_IDS_ = [IOSIntArray arrayWithInts:(int[]){
#line 83
            ComFqLibRecordRecordConstants_TYPE_ADMISSION, ComFqLibRecordRecordConstants_TYPE_EXAMINATION, ComFqLibRecordRecordConstants_TYPE_MEDICAL_IMAGING, ComFqLibRecordRecordConstants_TYPE_OUTPATIENTS, ComFqLibRecordRecordConstants_TYPE_SUGERY, ComFqLibRecordRecordConstants_TYPE_DISCHARGE, ComFqLibRecordRecordConstants_TYPE_OTHERS } count:7];
            ComFqLibRecordRecordConstants_MENZEHN_IDS_ = [IOSIntArray arrayWithInts:(int[]){
#line 84
              ComFqLibRecordRecordConstants_TYPE_DOORCASE, ComFqLibRecordRecordConstants_TYPE_EXAMINATION, ComFqLibRecordRecordConstants_TYPE_MEDICAL_IMAGING, ComFqLibRecordRecordConstants_TYPE_DISCHARGE, ComFqLibRecordRecordConstants_TYPE_OTHERS } count:5];
              ComFqLibRecordRecordConstants_CHECK_ITEMS_ = [IOSIntArray arrayWithInts:(int[]){
#line 85
                ComFqLibRecordRecordConstants_TYPE_CT, ComFqLibRecordRecordConstants_TYPE_XINDIAN, ComFqLibRecordRecordConstants_TYPE_CHAOSHENG } count:3];
                ComFqLibRecordRecordConstants_TYPE_ABSTRACT_ = [IOSObjectArray arrayWithObjects:(id[]){
#line 87
                  @"", @"\u521d\u6b65\u8bca\u65ad", @"\u5f02\u5e38\u9879", @"\u624b\u672f\u524d\u8bca\u65ad", @"\u9879\u76ee", @"\u51fa\u9662\u8bca\u65ad", @"\u6458\u8981\u4fe1\u606f", @"", @"", @"\u4e0a\u4f20\u65f6\u95f4", @"\u67e5\u623f\u65f6\u95f4" } count:11 type:[IOSClass classWithClass:[NSString class]]];
                  ComFqLibRecordRecordConstants_initialized = YES;
                }
              }

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getTypeNameByRecordTypeWithInt:", "getTypeNameByRecordType", "Ljava.lang.String;", 0x9, NULL },
    { "getTypeTitleByRecordTypeWithInt:", "getTypeTitleByRecordType", "Ljava.lang.String;", 0x9, NULL },
    { "getRecordTypeByUIIndexWithInt:", "getRecordTypeByUIIndex", "I", 0x9, NULL },
    { "getTypesByRecordTypeWithInt:", "getTypesByRecordType", "[I", 0x9, NULL },
    { "getCheckItemIds", NULL, "[I", 0x9, NULL },
    { "getAbstractByTypeWithInt:", "getAbstractByType", "Ljava.lang.String;", 0x9, NULL },
    { "getBigTypeWithComFqHalcyonEntityRecordItem:", "getBigType", "I", 0x9, NULL },
    { "getBigTypeWithComFqHalcyonEntityRecordItemSamp:", "getBigType", "I", 0x9, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "RECORD_TYPE_DOORCASE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_RECORD_TYPE_DOORCASE },
    { "RECORD_TYPE_ADMISSION_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_RECORD_TYPE_ADMISSION },
    { "MEDICAL_FROM_OWN_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_MEDICAL_FROM_OWN },
    { "MEDICAL_FROM_SHARE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_MEDICAL_FROM_SHARE },
    { "RECORD_FROM_OWN_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_RECORD_FROM_OWN },
    { "RECORD_FROM_SHARE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_RECORD_FROM_SHARE },
    { "SHARE_PATIENT_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_SHARE_PATIENT },
    { "SHARE_RECORD_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_SHARE_RECORD },
    { "SHARE_RECORD_ITEM_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_SHARE_RECORD_ITEM },
    { "TYPE_ADMISSION_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_ADMISSION },
    { "TYPE_EXAMINATION_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_EXAMINATION },
    { "TYPE_SUGERY_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_SUGERY },
    { "TYPE_MEDICAL_IMAGING_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_MEDICAL_IMAGING },
    { "TYPE_DISCHARGE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_DISCHARGE },
    { "TYPE_DOORCASE_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_DOORCASE },
    { "TYPE_OTHERS_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_OTHERS },
    { "TYPE_OUTPATIENTS_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_OUTPATIENTS },
    { "TYPE_CT_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_CT },
    { "TYPE_XINDIAN_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_XINDIAN },
    { "TYPE_CHAOSHENG_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqLibRecordRecordConstants_TYPE_CHAOSHENG },
    { "TYTE_NAME_", NULL, 0x1a, "[Ljava.lang.String;", &ComFqLibRecordRecordConstants_TYTE_NAME_,  },
    { "TYTE_TITLE_", NULL, 0x1a, "[Ljava.lang.String;", &ComFqLibRecordRecordConstants_TYTE_TITLE_,  },
    { "TYPES_", NULL, 0x19, "[I", &ComFqLibRecordRecordConstants_TYPES_,  },
    { "ZHUYUAN_IDS_", NULL, 0x1a, "[I", &ComFqLibRecordRecordConstants_ZHUYUAN_IDS_,  },
    { "MENZEHN_IDS_", NULL, 0x1a, "[I", &ComFqLibRecordRecordConstants_MENZEHN_IDS_,  },
    { "CHECK_ITEMS_", NULL, 0x1a, "[I", &ComFqLibRecordRecordConstants_CHECK_ITEMS_,  },
    { "TYPE_ABSTRACT_", NULL, 0x1a, "[Ljava.lang.String;", &ComFqLibRecordRecordConstants_TYPE_ABSTRACT_,  },
  };
  static J2ObjcClassInfo _ComFqLibRecordRecordConstants = { "RecordConstants", "com.fq.lib.record", NULL, 0x1, 9, methods, 27, fields, 0, NULL};
  return &_ComFqLibRecordRecordConstants;
}

@end
