//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic/SaveCDSLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic/SaveCDSLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "FQHttpParams.h"
#include "FQLog.h"
#include "HttpRequestPotocol.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "SaveCDSLogic.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/HashMap.h"


#line 15
@implementation ComFqHalcyonLogicSaveCDSLogic

- (void)saveCityWithNSString:(NSString *)cityName {
  
#line 18
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"city_name" withId:cityName];
  FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
  
#line 24
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:[NSString stringWithFormat:@"%@/doctors/save_city.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()] withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_BROW() withHalcyonHttpResponseHandle:
#line 25
  [[ComFqHalcyonLogicSaveCDSLogic_$1 alloc] init]];
}


#line 39
- (void)saveDepartmentWithNSString:(NSString *)department {
  
#line 40
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"dept_name" withId:department];
  FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
  
#line 56
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:[NSString stringWithFormat:@"%@/doctors/save_department.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()] withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_BROW() withHalcyonHttpResponseHandle:[[ComFqHalcyonLogicSaveCDSLogic_$2 alloc] init]];
}


#line 70
- (void)saveHospitalWithNSString:(NSString *)hospital
                    withNSString:(NSString *)city {
  
#line 71
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"hospital_name" withId:hospital];
  (void) [map putWithId:@"city_name" withId:city];
  FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
  
#line 77
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:[NSString stringWithFormat:@"%@/doctors/save_hospital.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()] withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:[[ComFqHalcyonLogicSaveCDSLogic_$3 alloc] init]];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "saveCityWithNSString:", "saveCity", "V", 0x1, NULL },
    { "saveDepartmentWithNSString:", "saveDepartment", "V", 0x1, NULL },
    { "saveHospitalWithNSString:withNSString:", "saveHospital", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic = { "SaveCDSLogic", "com.fq.halcyon.logic", NULL, 0x1, 4, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic;
}

@end

@interface ComFqHalcyonLogicSaveCDSLogic_FeedSaveHospital : NSObject
@end

@implementation ComFqHalcyonLogicSaveCDSLogic_FeedSaveHospital

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic_FeedSaveHospital = { "FeedSaveHospital", "com.fq.halcyon.logic", "SaveCDSLogic", 0x201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic_FeedSaveHospital;
}

@end

@interface ComFqHalcyonLogicSaveCDSLogic_FeedSaveDepartment : NSObject
@end

@implementation ComFqHalcyonLogicSaveCDSLogic_FeedSaveDepartment

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic_FeedSaveDepartment = { "FeedSaveDepartment", "com.fq.halcyon.logic", "SaveCDSLogic", 0x201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic_FeedSaveDepartment;
}

@end

@interface ComFqHalcyonLogicSaveCDSLogic_FeedSaveCity : NSObject
@end

@implementation ComFqHalcyonLogicSaveCDSLogic_FeedSaveCity

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic_FeedSaveCity = { "FeedSaveCity", "com.fq.halcyon.logic", "SaveCDSLogic", 0x201, 0, NULL, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic_FeedSaveCity;
}

@end

@implementation ComFqHalcyonLogicSaveCDSLogic_$1


#line 28
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 29
  [ComFqLibToolsFQLog iWithNSString:@"error" withNSString:[NSString stringWithFormat:@"msg:%@", e]];
}


#line 33
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 34
  [ComFqLibToolsFQLog iWithNSString:@"error" withNSString:[NSString stringWithFormat:@"results:%@", [nil_chk(results) description]]];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic_$1 = { "$1", "com.fq.halcyon.logic", "SaveCDSLogic", 0x8000, 3, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic_$1;
}

@end

@implementation ComFqHalcyonLogicSaveCDSLogic_$2


#line 59
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  [ComFqLibToolsFQLog iWithNSString:@"error" withNSString:[NSString stringWithFormat:@"msg:%@", e]];
}

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 65
  [ComFqLibToolsFQLog iWithNSString:@"error" withNSString:[NSString stringWithFormat:@"results:%@", [nil_chk(results) description]]];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic_$2 = { "$2", "com.fq.halcyon.logic", "SaveCDSLogic", 0x8000, 3, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic_$2;
}

@end

@implementation ComFqHalcyonLogicSaveCDSLogic_$3


#line 80
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 81
  [ComFqLibToolsFQLog iWithNSString:@"error" withNSString:[NSString stringWithFormat:@"msg:%@", e]];
}


#line 85
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 86
  [ComFqLibToolsFQLog iWithNSString:@"error" withNSString:[NSString stringWithFormat:@"results:%@", [nil_chk(results) description]]];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogicSaveCDSLogic_$3 = { "$3", "com.fq.halcyon.logic", "SaveCDSLogic", 0x8000, 3, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogicSaveCDSLogic_$3;
}

@end
