//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/SearchFollowUpTempleDetailLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/SearchFollowUpTempleDetailLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "FQHttpParams.h"
#include "FollowUpTemple.h"
#include "HttpRequestPotocol.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "SearchFollowUpTempleDetailLogic.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/HashMap.h"


#line 16
@implementation ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic


#line 58
- (id)initWithComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface:(id<ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface>)mIn
                                                                                                 withInt:(int)templeId {
  if (self = [super init]) {
    mHandle_ =
#line 56
    [[ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicHandle alloc] initWithComFqHalcyonLogic2SearchFollowUpTempleDetailLogic:self];
    
#line 59
    self->mInterface_ = mIn;
    
#line 60
    self->mFollowUpTempleId_ = templeId;
  }
  return self;
}


#line 63
- (void)getTempleDetail {
  
#line 64
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"followup_template_id" withId:[JavaLangInteger valueOfWithInt:mFollowUpTempleId_]];
  FQJSONObject *json = [ComFqLibJsonHelper createJsonForDebugWithJavaUtilMap:map];
  NSString *url = [NSString stringWithFormat:@"%@/timer/search_followup_template_detail.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  
#line 70
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:mHandle_];
}

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic *)other {
  [super copyAllFieldsTo:other];
  other->mFollowUpTemple_ = mFollowUpTemple_;
  other->mFollowUpTempleId_ = mFollowUpTempleId_;
  other->mHandle_ = mHandle_;
  other->mInterface_ = mInterface_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface:withInt:", "SearchFollowUpTempleDetailLogic", NULL, 0x1, NULL },
    { "getTempleDetail", NULL, "V", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mInterface_", NULL, 0x2, "Lcom.fq.halcyon.logic2.SearchFollowUpTempleDetailLogic$SearchFollowUpTempleDetailLogicInterface;", NULL,  },
    { "mFollowUpTempleId_", NULL, 0x2, "I", NULL,  },
    { "mFollowUpTemple_", NULL, 0x2, "Lcom.fq.halcyon.entity.FollowUpTemple;", NULL,  },
    { "mHandle_", NULL, 0x2, "Lcom.fq.halcyon.logic2.SearchFollowUpTempleDetailLogic$SearchFollowUpTempleDetailLogicHandle;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic = { "SearchFollowUpTempleDetailLogic", "com.fq.halcyon.logic2", NULL, 0x1, 2, methods, 4, fields, 0, NULL};
  return &_ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic;
}

@end

@interface ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface : NSObject
@end

@implementation ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onSearchErrorWithInt:withNSString:", "onSearchError", "V", 0x401, NULL },
    { "onSearchSuccessWithComFqHalcyonEntityFollowUpTemple:", "onSearchSuccess", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface = { "SearchFollowUpTempleDetailLogicInterface", "com.fq.halcyon.logic2", "SearchFollowUpTempleDetailLogic", 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface;
}

@end


#line 32
@implementation ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicHandle


#line 35
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 36
  [((id<ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface>) nil_chk(this$0_->mInterface_)) onSearchErrorWithInt:code withNSString:[((JavaLangThrowable *) nil_chk(e)) description]];
}


#line 40
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    FQJSONObject *mJsonObject = (FQJSONObject *) check_class_cast(results, [FQJSONObject class]);
    this$0_->mFollowUpTemple_ = [[ComFqHalcyonEntityFollowUpTemple alloc] init];
    [this$0_->mFollowUpTemple_ setAtttributeByjsonWithFQJSONObject:mJsonObject];
    [this$0_->mFollowUpTemple_ setmTempleIdWithInt:this$0_->mFollowUpTempleId_];
    [this$0_->mFollowUpTemple_ setUserIdWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]];
    [((id<ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface>) nil_chk(this$0_->mInterface_)) onSearchSuccessWithComFqHalcyonEntityFollowUpTemple:this$0_->mFollowUpTemple_];
  }
  else {
    
#line 50
    [((id<ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicInterface>) nil_chk(this$0_->mInterface_)) onSearchErrorWithInt:responseCode withNSString:msg];
  }
}

- (id)initWithComFqHalcyonLogic2SearchFollowUpTempleDetailLogic:(ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic *)outer$ {
  this$0_ = outer$;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2SearchFollowUpTempleDetailLogic:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.SearchFollowUpTempleDetailLogic;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicHandle = { "SearchFollowUpTempleDetailLogicHandle", "com.fq.halcyon.logic2", "SearchFollowUpTempleDetailLogic", 0x0, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2SearchFollowUpTempleDetailLogic_SearchFollowUpTempleDetailLogicHandle;
}

@end
