//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/SendFollowUpLeaveMessageLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_H_
#define _ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_H_

@class ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicHandle;
@class JavaLangThrowable;
@protocol ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicInterface;

#import "JreEmulation.h"
#include "FQHttpResponseInterface.h"
#include "HalcyonHttpResponseHandle.h"

@interface ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic : NSObject {
 @public
  __weak id<ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicInterface> mInterface_;
  ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicHandle *mHandle_;
}

- (id)initWithComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicInterface:(id<ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicInterface>)mIn;

- (void)submitMessageWithNSString:(NSString *)message
                          withInt:(int)mTimerId;

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic, mHandle_, ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicHandle *)

@protocol ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicInterface < ComFqHttpPotocolFQHttpResponseInterface, NSObject, JavaObject >
- (void)onSubmitMessageErrorWithInt:(int)code
                       withNSString:(NSString *)msg;

- (void)onSubmitMessageSuccess;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicInterface_init() {}

@interface ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicHandle : HalcyonHttpResponseHandle {
 @public
  ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic *this$0_;
}

- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e;

- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results;

- (id)initWithComFqHalcyonLogic2SendFollowUpLeaveMessageLogic:(ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicHandle_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_SendFollowUpLeaveMessageLogicHandle, this$0_, ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic *)

#endif // _ComFqHalcyonLogic2SendFollowUpLeaveMessageLogic_H_
