//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/SettingLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/SettingLogic.java"

#include "SettingLogic.h"


#line 3
@implementation ComFqHalcyonLogic2SettingLogic

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2SettingLogic = { "SettingLogic", "com.fq.halcyon.logic2", NULL, 0x1, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2SettingLogic;
}

@end
