//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/record/SnapPhotoManager.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqLibRecordSnapPhotoManager_H_
#define _ComFqLibRecordSnapPhotoManager_H_

@class ComFqHalcyonEntityPhotoRecord;
@class ComFqHalcyonUimodelsOneCopy;
@class ComFqHalcyonUimodelsOneType;
@class IOSIntArray;
@class JavaUtilArrayList;

#import "JreEmulation.h"

@interface ComFqLibRecordSnapPhotoManager : NSObject {
 @public
  JavaUtilArrayList *mTypes_;
  IOSIntArray *TYPES_;
  ComFqHalcyonUimodelsOneCopy *mCurrentCopy_;
  int mCurrentIndex_;
  int mUIIndex_;
  int mRecordId_;
  BOOL mIsAllowRu_;
  BOOL mIsAllowChu_;
  id mTakePhoto_;
}

- (id)init;

- (id)getTakePhoto;

- (void)setTakePhotoWithId:(id)obj;

+ (ComFqLibRecordSnapPhotoManager *)instanceWithInt:(int)recordId
                                            withInt:(int)docType
                                            withInt:(int)currType
                                        withBoolean:(BOOL)isRu
                                        withBoolean:(BOOL)isChu;

+ (ComFqLibRecordSnapPhotoManager *)getInstance;

- (int)getRecordId;

- (JavaUtilArrayList *)getTypes;

- (JavaUtilArrayList *)getRealyTypes;

- (void)clear;

- (int)getPhotoCount;

- (BOOL)isHaveTypeWithInt:(int)recordType;

- (int)getTypeCount;

- (ComFqHalcyonUimodelsOneType *)getTypeByIndexWithInt:(int)index;

- (ComFqHalcyonUimodelsOneType *)getLastType;

- (ComFqHalcyonEntityPhotoRecord *)getLastPhoto;

- (void)addTypeWithInt:(int)index
withComFqHalcyonUimodelsOneType:(ComFqHalcyonUimodelsOneType *)type;

- (ComFqHalcyonUimodelsOneType *)getCurrentType;

- (int)getCurrentIndex;

- (ComFqHalcyonUimodelsOneCopy *)getCurrentCopy;

- (NSString *)getCurrenTypeName;

- (int)getCurrentTypePhotoCount;

- (void)addCurrentIndexWithInt:(int)plus;

- (BOOL)isAllowCatch;

- (BOOL)isSignlePhoto;

- (void)selectIndexWithInt:(int)index;

- (void)lastRecordItem;

- (void)nextRecordItem;

- (BOOL)canNextRecordItem;

- (BOOL)isChangeType;

- (void)lastRecordType;

- (void)nextRecordType;

- (NSString *)getSelectTypeName;

- (void)initCurrentType OBJC_METHOD_FAMILY_NONE;

- (void)currentCopyAddPhotoWithNSString:(NSString *)path;

- (void)reSetData;

- (void)setToTypeInFirstWithInt:(int)type;

- (void)copyAllFieldsTo:(ComFqLibRecordSnapPhotoManager *)other;

@end

__attribute__((always_inline)) inline void ComFqLibRecordSnapPhotoManager_init() {}

J2OBJC_FIELD_SETTER(ComFqLibRecordSnapPhotoManager, mTypes_, JavaUtilArrayList *)
J2OBJC_FIELD_SETTER(ComFqLibRecordSnapPhotoManager, TYPES_, IOSIntArray *)
J2OBJC_FIELD_SETTER(ComFqLibRecordSnapPhotoManager, mCurrentCopy_, ComFqHalcyonUimodelsOneCopy *)
J2OBJC_FIELD_SETTER(ComFqLibRecordSnapPhotoManager, mTakePhoto_, id)

FOUNDATION_EXPORT ComFqLibRecordSnapPhotoManager *ComFqLibRecordSnapPhotoManager_mInstance_;
J2OBJC_STATIC_FIELD_GETTER(ComFqLibRecordSnapPhotoManager, mInstance_, ComFqLibRecordSnapPhotoManager *)
J2OBJC_STATIC_FIELD_SETTER(ComFqLibRecordSnapPhotoManager, mInstance_, ComFqLibRecordSnapPhotoManager *)

#endif // _ComFqLibRecordSnapPhotoManager_H_
