//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/TagLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/TagLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "Contacts.h"
#include "FQHttpParams.h"
#include "FQLog.h"
#include "HttpRequestPotocol.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "IOSPrimitiveArray.h"
#include "JSONArray.h"
#include "JSONException.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "Tag.h"
#include "TagLogic.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/ArrayList.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"


#line 22
@implementation ComFqHalcyonLogic2TagLogic


#line 30
- (void)getListAllTagsWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:(id<ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack>)callback {
  
#line 31
  id<JavaUtilMap> map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  NSString *url = [NSString stringWithFormat:@"%@/tags/list_all_tags.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_BROW() withHalcyonHttpResponseHandle:
#line 36
  [[ComFqHalcyonLogic2TagLogic_$1 alloc] initWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:callback]];
}


#line 94
- (void)addTagWithNSString:(NSString *)tag
withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)callback {
  
#line 95
  id<JavaUtilMap> map = [[JavaUtilHashMap alloc] init];
  IOSObjectArray *tags = [IOSObjectArray arrayWithObjects:(id[]){ tag } count:1 type:[IOSClass classWithClass:[NSString class]]];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  @try {
    (void) [map putWithId:@"tag" withId:[[FQJSONArray alloc] initWithId:tags]];
  }
  @catch (
#line 100
  FQJSONException *e) {
    [((FQJSONException *) nil_chk(e)) printStackTrace];
  }
  NSString *url = [NSString stringWithFormat:@"%@/tags/add_tag.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 106
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 107
  [[ComFqHalcyonLogic2TagLogic_$2 alloc] initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:callback withNSString:tag]];
}


#line 141
- (void)addTagWithJavaUtilArrayList:(JavaUtilArrayList *)tagList
              withJavaUtilArrayList:(JavaUtilArrayList *)patientIdList
withComFqHalcyonLogic2TagLogic_SuccessCallBack:(id<ComFqHalcyonLogic2TagLogic_SuccessCallBack>)success
withComFqHalcyonLogic2TagLogic_FailCallBack:(id<ComFqHalcyonLogic2TagLogic_FailCallBack>)fail {
  
#line 144
  id<JavaUtilMap> map = [[JavaUtilHashMap alloc] init];
  FQJSONArray *arrayPatient = [[FQJSONArray alloc] initWithJavaUtilCollection:patientIdList];
  FQJSONArray *arrayTag = [[FQJSONArray alloc] initWithJavaUtilCollection:tagList];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"tag" withId:arrayTag];
  (void) [map putWithId:@"doctor_patient_id" withId:arrayPatient];
  NSString *url = [NSString stringWithFormat:@"%@/tags/add_tag_doctor_patient_id.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  
#line 152
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 155
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 156
  [[ComFqHalcyonLogic2TagLogic_$3 alloc] initWithComFqHalcyonLogic2TagLogic_FailCallBack:fail withComFqHalcyonLogic2TagLogic_SuccessCallBack:success]];
}


#line 192
- (void)delTagWithJavaUtilArrayList:(JavaUtilArrayList *)tagIdList
withComFqHalcyonLogic2TagLogic_SuccessCallBack:(id<ComFqHalcyonLogic2TagLogic_SuccessCallBack>)success
withComFqHalcyonLogic2TagLogic_FailCallBack:(id<ComFqHalcyonLogic2TagLogic_FailCallBack>)fail {
  
#line 194
  id<JavaUtilMap> map = [[JavaUtilHashMap alloc] init];
  FQJSONArray *array = [[FQJSONArray alloc] initWithJavaUtilCollection:tagIdList];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"tag_id" withId:array];
  NSString *url = [NSString stringWithFormat:@"%@/tags/delete_tag.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 202
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 203
  [[ComFqHalcyonLogic2TagLogic_$4 alloc] initWithComFqHalcyonLogic2TagLogic_FailCallBack:fail withJavaUtilArrayList:tagIdList withComFqHalcyonLogic2TagLogic_SuccessCallBack:success]];
}


#line 247
- (void)getPatientIdTagsWithJavaUtilArrayList:(JavaUtilArrayList *)patientIdList
withComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:(id<ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack>)callBack {
  
#line 249
  id<JavaUtilMap> map = [[JavaUtilHashMap alloc] init];
  FQJSONArray *array = [[FQJSONArray alloc] initWithJavaUtilCollection:patientIdList];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"doctor_patient_id" withId:array];
  NSString *url = [NSString stringWithFormat:@"%@/tags/list_tags_doctor_patient_id.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  
#line 255
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 257
  [[ComFqHalcyonLogic2TagLogic_$5 alloc] initWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:callBack]];
}


#line 355
- (void)attachPatientsWithJavaUtilArrayList:(JavaUtilArrayList *)patientIdList
                      withJavaUtilArrayList:(JavaUtilArrayList *)addTagIdList
                      withJavaUtilArrayList:(JavaUtilArrayList *)addTagStrList
                      withJavaUtilArrayList:(JavaUtilArrayList *)delTagIdList
withComFqHalcyonLogic2TagLogic_SuccessCallBack:(id<ComFqHalcyonLogic2TagLogic_SuccessCallBack>)onSuccess
withComFqHalcyonLogic2TagLogic_FailCallBack:(id<ComFqHalcyonLogic2TagLogic_FailCallBack>)onFail {
  
#line 359
  id<JavaUtilMap> map = [[JavaUtilHashMap alloc] init];
  id<JavaUtilMap> setMap = [[JavaUtilHashMap alloc] init];
  id<JavaUtilMap> removeMap = [[JavaUtilHashMap alloc] init];
  FQJSONArray *patientIdArray = [[FQJSONArray alloc] initWithJavaUtilCollection:patientIdList];
  FQJSONArray *addTagIdArray = [[FQJSONArray alloc] initWithJavaUtilCollection:addTagIdList];
  FQJSONArray *addTagStrArray = [[FQJSONArray alloc] initWithJavaUtilCollection:addTagStrList];
  FQJSONArray *delTagIdArray = [[FQJSONArray alloc] initWithJavaUtilCollection:delTagIdList];
  (void) [setMap putWithId:@"user_friend_id" withId:patientIdArray];
  (void) [setMap putWithId:@"tag_id" withId:addTagIdArray];
  (void) [setMap putWithId:@"tag" withId:addTagStrArray];
  FQJSONObject *setJson = [[FQJSONObject alloc] initWithJavaUtilMap:setMap];
  (void) [removeMap putWithId:@"user_friend_id" withId:patientIdArray];
  (void) [removeMap putWithId:@"tag_id" withId:delTagIdArray];
  FQJSONObject *removeJson = [[FQJSONObject alloc] initWithJavaUtilMap:removeMap];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"tag_set" withId:setJson];
  (void) [map putWithId:@"tag_remove" withId:removeJson];
  NSString *url = [NSString stringWithFormat:@"%@/tags/attach_patients.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 380
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 381
  [[ComFqHalcyonLogic2TagLogic_$6 alloc] initWithComFqHalcyonLogic2TagLogic_FailCallBack:onFail withComFqHalcyonLogic2TagLogic_SuccessCallBack:onSuccess]];
}


#line 408
- (void)modifyTagContactWithIntArray:(IOSIntArray *)adddocPatId
                        withIntArray:(IOSIntArray *)addTagIds
               withJavaUtilArrayList:(JavaUtilArrayList *)tagTitils
                        withIntArray:(IOSIntArray *)remdocPatIds
                        withIntArray:(IOSIntArray *)remTagIds
withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)callback {
  
#line 411
  IOSObjectArray *tagTitilst = nil;
  if (tagTitils != nil) {
    tagTitilst = [IOSObjectArray arrayWithLength:[tagTitils size] type:[IOSClass classWithClass:[NSString class]]];
    (void) [tagTitils toArrayWithNSObjectArray:tagTitilst];
  }
  [self modifyTagContactWithIntArray:adddocPatId withIntArray:addTagIds withNSStringArray:tagTitilst withIntArray:remdocPatIds withIntArray:
#line 417
  remTagIds withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:callback];
}


#line 420
- (void)modifyTagContactWithIntArray:(IOSIntArray *)adddocPatId
                        withIntArray:(IOSIntArray *)addTagIds
                   withNSStringArray:(IOSObjectArray *)tagTitils
                        withIntArray:(IOSIntArray *)remdocPatIds
                        withIntArray:(IOSIntArray *)remTagIds
withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)callback {
  
#line 423
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  if (adddocPatId != nil) {
    FQJSONObject *addJson = [[FQJSONObject alloc] init];
    @try {
      (void) [addJson putWithNSString:@"user_friend_id" withId:[[FQJSONArray alloc] initWithId:adddocPatId]];
      
#line 431
      if (addTagIds != nil) {
        FQJSONArray *addTagId = [[FQJSONArray alloc] initWithId:addTagIds];
        (void) [addJson putWithNSString:@"tag_id" withId:addTagId];
      }
      
#line 436
      if (tagTitils != nil) {
        FQJSONArray *addTagTitle = [[FQJSONArray alloc] initWithId:tagTitils];
        (void) [addJson putWithNSString:@"tag" withId:addTagTitle];
      }
      (void) [map putWithId:@"tag_set" withId:addJson];
    }
    @catch (
#line 441
    FQJSONException *e) {
      [((FQJSONException *) nil_chk(e)) printStackTrace];
    }
  }
  
#line 446
  if (remdocPatIds != nil) {
    FQJSONObject *removeJson = [[FQJSONObject alloc] init];
    @try {
      (void) [removeJson putWithNSString:@"user_friend_id" withId:[[FQJSONArray alloc] initWithId:remdocPatIds]];
      
#line 451
      if (remTagIds != nil) {
        (void) [removeJson putWithNSString:@"tag_id" withId:[[FQJSONArray alloc] initWithId:remTagIds]];
      }
      (void) [map putWithId:@"tag_remove" withId:removeJson];
    }
    @catch (
#line 455
    FQJSONException *e) {
      [((FQJSONException *) nil_chk(e)) printStackTrace];
    }
  }
  
#line 460
  NSString *url = [NSString stringWithFormat:@"%@/tags/attach_patients.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  
#line 463
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 464
  [[ComFqHalcyonLogic2TagLogic_$7 alloc] initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:callback]];
}


#line 504
- (void)modifyTagWithComFqHalcyonEntityTag:(ComFqHalcyonEntityTag *)tag
withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)callback {
  
#line 505
  JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
  (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
  (void) [map putWithId:@"tag_id" withId:[((FQJSONArray *) [[FQJSONArray alloc] init]) putWithInt:[((ComFqHalcyonEntityTag *) nil_chk(tag)) getId]]];
  (void) [map putWithId:@"tag_title" withId:[tag getTitle]];
  
#line 510
  NSString *url = [NSString stringWithFormat:@"%@/tags/modify_tags_title.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()];
  ComFqHttpAsyncFQHttpParams *params = [[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:[ComFqLibJsonHelper createJsonWithJavaUtilMap:map]];
  (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:url withComFqHttpAsyncFQHttpParams:params withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:
#line 513
  [[ComFqHalcyonLogic2TagLogic_$8 alloc] initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:callback]];
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getListAllTagsWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:", "getListAllTags", "V", 0x1, NULL },
    { "addTagWithNSString:withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:", "addTag", "V", 0x1, NULL },
    { "addTagWithJavaUtilArrayList:withJavaUtilArrayList:withComFqHalcyonLogic2TagLogic_SuccessCallBack:withComFqHalcyonLogic2TagLogic_FailCallBack:", "addTag", "V", 0x1, NULL },
    { "delTagWithJavaUtilArrayList:withComFqHalcyonLogic2TagLogic_SuccessCallBack:withComFqHalcyonLogic2TagLogic_FailCallBack:", "delTag", "V", 0x1, NULL },
    { "getPatientIdTagsWithJavaUtilArrayList:withComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:", "getPatientIdTags", "V", 0x1, NULL },
    { "attachPatientsWithJavaUtilArrayList:withJavaUtilArrayList:withJavaUtilArrayList:withJavaUtilArrayList:withComFqHalcyonLogic2TagLogic_SuccessCallBack:withComFqHalcyonLogic2TagLogic_FailCallBack:", "attachPatients", "V", 0x1, NULL },
    { "modifyTagContactWithIntArray:withIntArray:withJavaUtilArrayList:withIntArray:withIntArray:withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:", "modifyTagContact", "V", 0x1, NULL },
    { "modifyTagContactWithIntArray:withIntArray:withNSStringArray:withIntArray:withIntArray:withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:", "modifyTagContact", "V", 0x1, NULL },
    { "modifyTagWithComFqHalcyonEntityTag:withComFqHalcyonLogic2TagLogic_OnTagModifyCallback:", "modifyTag", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic = { "TagLogic", "com.fq.halcyon.logic2", NULL, 0x1, 10, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic;
}

@end

@interface ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack : NSObject
@end

@implementation ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "resTagListWithJavaUtilArrayList:", "resTagList", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack = { "RequestTagInfCallBack", "com.fq.halcyon.logic2", "TagLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack;
}

@end

@interface ComFqHalcyonLogic2TagLogic_RequestPatientListCallBack : NSObject
@end

@implementation ComFqHalcyonLogic2TagLogic_RequestPatientListCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getPatientListWithJavaUtilArrayList:", "getPatientList", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_RequestPatientListCallBack = { "RequestPatientListCallBack", "com.fq.halcyon.logic2", "TagLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_RequestPatientListCallBack;
}

@end

@interface ComFqHalcyonLogic2TagLogic_OnTagModifyCallback : NSObject
@end

@implementation ComFqHalcyonLogic2TagLogic_OnTagModifyCallback

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onSuccessWithComFqHalcyonEntityTag:", "onSuccess", "V", 0x401, NULL },
    { "onModifySuccessWithBoolean:", "onModifySuccess", "V", 0x401, NULL },
    { "addTagWithComFqHalcyonEntityTag:", "addTag", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_OnTagModifyCallback = { "OnTagModifyCallback", "com.fq.halcyon.logic2", "TagLogic", 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_OnTagModifyCallback;
}

@end

@interface ComFqHalcyonLogic2TagLogic_SuccessCallBack : NSObject
@end

@implementation ComFqHalcyonLogic2TagLogic_SuccessCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onSuccessWithInt:withNSString:withInt:withId:", "onSuccess", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_SuccessCallBack = { "SuccessCallBack", "com.fq.halcyon.logic2", "TagLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_SuccessCallBack;
}

@end

@interface ComFqHalcyonLogic2TagLogic_FailCallBack : NSObject
@end

@implementation ComFqHalcyonLogic2TagLogic_FailCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onFailWithInt:withNSString:", "onFail", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_FailCallBack = { "FailCallBack", "com.fq.halcyon.logic2", "TagLogic", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_FailCallBack;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$1


#line 39
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 40
  [ComFqLibToolsFQLog iWithNSString:@"getListAllTags error" withNSString:[NSString stringWithFormat:@"~~~~msg:%@", e]];
  if (ComFqLibToolsConstants_get_tagList_() == nil) {
    (void) ComFqLibToolsConstants_set_tagList_([[JavaUtilArrayList alloc] init]);
  }
}


#line 47
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0 && type == 2) {
    FQJSONArray *array = (FQJSONArray *) check_class_cast(results, [FQJSONArray class]);
    JavaUtilArrayList *tags = [[JavaUtilArrayList alloc] init];
    for (int i = 0, count = [((FQJSONArray *) nil_chk(array)) length]; i < count; i++) {
      @try {
        
#line 57
        ComFqHalcyonEntityTag *tag = [[ComFqHalcyonEntityTag alloc] init];
        [tag setAtttributeByjsonWithFQJSONObject:[array getJSONObjectWithInt:
#line 59
        i]];
        [tags addWithId:tag];
        
#line 62
        if (ComFqLibToolsConstants_get_contactsList_() != nil) {
          for (ComFqHalcyonEntityContacts * __strong user in ComFqLibToolsConstants_get_contactsList_()) {
            JavaUtilArrayList *tgs = [((ComFqHalcyonEntityContacts *) nil_chk(user)) getTags];
            for (NSString * __strong tg in nil_chk(tgs)) {
              if ([((NSString *) nil_chk(tg)) isEqual:[tag getTitle]]) {
                [tag addContactsWithComFqHalcyonEntityContacts:user];
                break;
              }
            }
          }
        }
        [tag setCountWithInt:[((JavaUtilArrayList *) nil_chk([tag getContacts])) size]];
      }
      @catch (
#line 74
      FQJSONException *e) {
        [((FQJSONException *) nil_chk(e)) printStackTrace];
      }
    }
    (void) ComFqLibToolsConstants_set_tagList_(tags);
    if (val$callback_ != nil)
#line 80
    [val$callback_ resTagListWithJavaUtilArrayList:tags];
  }
  else {
    
#line 82
    [self onErrorWithInt:responseCode withJavaLangThrowable:[[JavaLangThrowable alloc] initWithNSString:msg]];
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:(id<ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack>)capture$0 {
  val$callback_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callback_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$RequestTagInfCallBack;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$1 = { "$1", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$1;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$2


#line 108
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 109
  [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onModifySuccessWithBoolean:NO];
}


#line 113
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    ComFqHalcyonEntityTag *tg = [[ComFqHalcyonEntityTag alloc] init];
    [tg setIdWithInt:[((FQJSONObject *) nil_chk(((FQJSONObject *) check_class_cast(results, [FQJSONObject class])))) optIntWithNSString:@"tag_id"]];
    [tg setTitleWithNSString:val$tag_];
    [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) addTagWithComFqHalcyonEntityTag:tg];
  }
  else {
    
#line 121
    [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onModifySuccessWithBoolean:NO];
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)capture$0
                                                withNSString:(NSString *)capture$1 {
  val$callback_ = capture$0;
  val$tag_ = capture$1;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:withNSString:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callback_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$OnTagModifyCallback;", NULL,  },
    { "val$tag_", NULL, 0x1012, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$2 = { "$2", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 2, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$2;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$3


#line 159
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 160
  if (val$fail_ != nil) {
    [val$fail_ onFailWithInt:code withNSString:[((JavaLangThrowable *) nil_chk(e)) getMessage]];
  }
}


#line 166
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    if (val$success_ != nil) {
      [val$success_ onSuccessWithInt:responseCode withNSString:msg withInt:type withId:
#line 171
      results];
    }
  }
  else {
    
#line 174
    if (val$fail_ != nil) {
      [val$fail_ onFailWithInt:responseCode withNSString:msg];
    }
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_FailCallBack:(id<ComFqHalcyonLogic2TagLogic_FailCallBack>)capture$0
       withComFqHalcyonLogic2TagLogic_SuccessCallBack:(id<ComFqHalcyonLogic2TagLogic_SuccessCallBack>)capture$1 {
  val$fail_ = capture$0;
  val$success_ = capture$1;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_FailCallBack:withComFqHalcyonLogic2TagLogic_SuccessCallBack:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$fail_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$FailCallBack;", NULL,  },
    { "val$success_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$SuccessCallBack;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$3 = { "$3", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 2, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$3;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$4


#line 206
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 207
  if (val$fail_ != nil) {
    [val$fail_ onFailWithInt:code withNSString:[((JavaLangThrowable *) nil_chk(e)) getMessage]];
  }
}


#line 213
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    if (val$tagIdList_ != nil) {
      
#line 218
      for (int j = 0; j < [((JavaUtilArrayList *) nil_chk(ComFqLibToolsConstants_get_tagList_())) size]; j++) {
        if ([((JavaLangInteger *) nil_chk([val$tagIdList_ getWithInt:0])) intValue] == [((ComFqHalcyonEntityTag *) nil_chk([ComFqLibToolsConstants_get_tagList_() getWithInt:
#line 220
        j])) getId]) {
          (void) [ComFqLibToolsConstants_get_tagList_() removeWithInt:j];
          break;
        }
      }
    }
    if (val$success_ != nil) {
      [val$success_ onSuccessWithInt:responseCode withNSString:msg withInt:type withId:
#line 228
      results];
    }
  }
  else {
    
#line 231
    if (val$fail_ != nil) {
      [val$fail_ onFailWithInt:responseCode withNSString:msg];
    }
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_FailCallBack:(id<ComFqHalcyonLogic2TagLogic_FailCallBack>)capture$0
                                withJavaUtilArrayList:(JavaUtilArrayList *)capture$1
       withComFqHalcyonLogic2TagLogic_SuccessCallBack:(id<ComFqHalcyonLogic2TagLogic_SuccessCallBack>)capture$2 {
  val$fail_ = capture$0;
  val$tagIdList_ = capture$1;
  val$success_ = capture$2;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_FailCallBack:withJavaUtilArrayList:withComFqHalcyonLogic2TagLogic_SuccessCallBack:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$fail_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$FailCallBack;", NULL,  },
    { "val$tagIdList_", NULL, 0x1012, "Ljava.util.ArrayList;", NULL,  },
    { "val$success_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$SuccessCallBack;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$4 = { "$4", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 3, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$4;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$5


#line 260
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 261
  [ComFqLibToolsFQLog iWithNSString:@"getPatientIdTags error" withNSString:[NSString stringWithFormat:@"msg:%@", e]];
}


#line 265
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0 && type == 2) {
    FQJSONArray *array = (FQJSONArray *) check_class_cast(results, [FQJSONArray class]);
    JavaUtilArrayList *tags = [[JavaUtilArrayList alloc] init];
    for (int i = 0, count = [((FQJSONArray *) nil_chk(array)) length]; i < count; i++) {
      @try {
        
#line 275
        ComFqHalcyonEntityTag *tag = [[ComFqHalcyonEntityTag alloc] init];
        [tag setAtttributeByjsonWithFQJSONObject:[array getJSONObjectWithInt:
#line 277
        i]];
        [tags addWithId:tag];
      }
      @catch (
#line 279
      FQJSONException *e) {
        [((FQJSONException *) nil_chk(e)) printStackTrace];
      }
    }
    if (val$callBack_ != nil)
#line 284
    [val$callBack_ resTagListWithJavaUtilArrayList:tags];
  }
  else {
    
#line 286
    [self onErrorWithInt:responseCode withJavaLangThrowable:[[JavaLangThrowable alloc] initWithNSString:msg]];
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:(id<ComFqHalcyonLogic2TagLogic_RequestTagInfCallBack>)capture$0 {
  val$callBack_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_RequestTagInfCallBack:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callBack_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$RequestTagInfCallBack;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$5 = { "$5", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$5;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$6


#line 384
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 386
  if (val$onFail_ != nil) {
    [val$onFail_ onFailWithInt:code withNSString:[((JavaLangThrowable *) nil_chk(e)) getMessage]];
  }
}


#line 392
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 394
  if (responseCode == 0) {
    if (val$onSuccess_ != nil) {
      [val$onSuccess_ onSuccessWithInt:responseCode withNSString:msg withInt:type withId:
#line 397
      results];
    }
  }
  else {
    
#line 400
    if (val$onFail_ != nil) {
      [val$onFail_ onFailWithInt:responseCode withNSString:msg];
    }
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_FailCallBack:(id<ComFqHalcyonLogic2TagLogic_FailCallBack>)capture$0
       withComFqHalcyonLogic2TagLogic_SuccessCallBack:(id<ComFqHalcyonLogic2TagLogic_SuccessCallBack>)capture$1 {
  val$onFail_ = capture$0;
  val$onSuccess_ = capture$1;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_FailCallBack:withComFqHalcyonLogic2TagLogic_SuccessCallBack:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$onFail_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$FailCallBack;", NULL,  },
    { "val$onSuccess_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$SuccessCallBack;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$6 = { "$6", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 2, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$6;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$7


#line 465
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 466
  [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onModifySuccessWithBoolean:NO];
}


#line 470
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    
#line 496
    [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onModifySuccessWithBoolean:YES];
  }
  else {
    
#line 498
    [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onModifySuccessWithBoolean:NO];
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)capture$0 {
  val$callback_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callback_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$OnTagModifyCallback;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$7 = { "$7", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$7;
}

@end

@implementation ComFqHalcyonLogic2TagLogic_$8


#line 515
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 516
  [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onSuccessWithComFqHalcyonEntityTag:nil];
}


#line 520
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0 && type == 1) {
    
#line 526
    ComFqHalcyonEntityTag *tag = [[ComFqHalcyonEntityTag alloc] init];
    [tag setAtttributeByjsonWithFQJSONObject:(FQJSONObject *) check_class_cast(results, [FQJSONObject class])];
    [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onSuccessWithComFqHalcyonEntityTag:tag];
  }
  else {
    
#line 530
    [((id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>) nil_chk(val$callback_)) onSuccessWithComFqHalcyonEntityTag:nil];
  }
}

- (id)initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:(id<ComFqHalcyonLogic2TagLogic_OnTagModifyCallback>)capture$0 {
  val$callback_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2TagLogic_OnTagModifyCallback:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callback_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.TagLogic$OnTagModifyCallback;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2TagLogic_$8 = { "$8", "com.fq.halcyon.logic2", "TagLogic", 0x8000, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2TagLogic_$8;
}

@end
