//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uilogic/TagUtils.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uilogic/TagUtils.java"

#include "Constants.h"
#include "Contacts.h"
#include "Tag.h"
#include "TagUtils.h"
#include "java/lang/Integer.h"
#include "java/util/ArrayList.h"


#line 14
@implementation ComFqHalcyonUilogicTagUtils


#line 24
- (JavaUtilArrayList *)getAddTagWithIdList {
  
#line 25
  return mAddTagWithIdList_;
}


#line 29
- (JavaUtilArrayList *)getAddTagWithStrList {
  return mAddTagWithStrList_;
}


#line 34
- (JavaUtilArrayList *)getDelTagList {
  
#line 35
  return mDelTagList_;
}


#line 42
- (JavaUtilArrayList *)getMyContactTagListWithComFqHalcyonEntityContacts:(ComFqHalcyonEntityContacts *)contact {
  
#line 43
  JavaUtilArrayList *mContactTagList = [[JavaUtilArrayList alloc] init];
  JavaUtilArrayList *tempTagList = [[JavaUtilArrayList alloc] init];
  [tempTagList addAllWithJavaUtilCollection:[((ComFqHalcyonEntityContacts *) nil_chk(contact)) getTags]];
  for (int i = 0; i < [tempTagList size]; i++) {
    BOOL b = YES;
    NSString *tagKey = [tempTagList getWithInt:i];
    for (int j = 0; j < [((JavaUtilArrayList *) nil_chk(ComFqLibToolsConstants_get_tagList_())) size] && b; j++) {
      ComFqHalcyonEntityTag *tag = [ComFqLibToolsConstants_get_tagList_() getWithInt:j];
      if ([((NSString *) nil_chk(tagKey)) isEqual:[((ComFqHalcyonEntityTag *) nil_chk(tag)) getTitle]]) {
        [mContactTagList addWithId:tag];
        b = NO;
      }
    }
  }
  return mContactTagList;
}


#line 65
- (void)getChangeListWithJavaUtilArrayList:(JavaUtilArrayList *)contactTagList
                     withJavaUtilArrayList:(JavaUtilArrayList *)resultTagList {
  
#line 67
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(contactTagList)) size]; i++) {
    ComFqHalcyonEntityTag *tag = [contactTagList getWithInt:i];
    if ([((JavaUtilArrayList *) nil_chk(resultTagList)) containsWithId:tag]) {
      continue;
    }
    else {
      
#line 72
      [((JavaUtilArrayList *) nil_chk(mDelTagList_)) addWithId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityTag *) nil_chk(tag)) getId]]];
    }
  }
  
#line 76
  for (int i = 0; i < [((JavaUtilArrayList *) nil_chk(resultTagList)) size]; i++) {
    ComFqHalcyonEntityTag *tag = [resultTagList getWithInt:i];
    if ([contactTagList containsWithId:tag]) {
      continue;
    }
    else {
      
#line 81
      if ([((ComFqHalcyonEntityTag *) nil_chk(tag)) getId] == -1) {
        [((JavaUtilArrayList *) nil_chk(mAddTagWithStrList_)) addWithId:[tag getTitle]];
      }
      else {
        
#line 84
        [((JavaUtilArrayList *) nil_chk(mAddTagWithIdList_)) addWithId:[JavaLangInteger valueOfWithInt:[tag getId]]];
      }
    }
  }
}

- (id)init {
  if (self = [super init]) {
    mAddTagWithIdList_ =
#line 17
    [[JavaUtilArrayList alloc] init];
    mAddTagWithStrList_ =
#line 19
    [[JavaUtilArrayList alloc] init];
    mDelTagList_ =
#line 21
    [[JavaUtilArrayList alloc] init];
  }
  return self;
}

- (void)copyAllFieldsTo:(ComFqHalcyonUilogicTagUtils *)other {
  [super copyAllFieldsTo:other];
  other->mAddTagWithIdList_ = mAddTagWithIdList_;
  other->mAddTagWithStrList_ = mAddTagWithStrList_;
  other->mDelTagList_ = mDelTagList_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getAddTagWithIdList", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "getAddTagWithStrList", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "getDelTagList", NULL, "Ljava.util.ArrayList;", 0x1, NULL },
    { "getMyContactTagListWithComFqHalcyonEntityContacts:", "getMyContactTagList", "Ljava.util.ArrayList;", 0x1, NULL },
    { "getChangeListWithJavaUtilArrayList:withJavaUtilArrayList:", "getChangeList", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mAddTagWithIdList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "mAddTagWithStrList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
    { "mDelTagList_", NULL, 0x2, "Ljava.util.ArrayList;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonUilogicTagUtils = { "TagUtils", "com.fq.halcyon.uilogic", NULL, 0x1, 6, methods, 3, fields, 0, NULL};
  return &_ComFqHalcyonUilogicTagUtils;
}

@end
