//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/TimerMember.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/TimerMember.java"

#include "Constants.h"
#include "JSONArray.h"
#include "JSONObject.h"
#include "TimerMember.h"
#include "User.h"


#line 9
@implementation ComFqHalcyonEntityTimerMember


#line 17
- (void)setAtttributeByjsonWithFQJSONArray:(FQJSONArray *)mArray {
  
#line 18
  if ([((FQJSONArray *) nil_chk(mArray)) length] != 0) {
    for (int i = 0; i < [mArray length]; i++) {
      FQJSONObject *mObject = [mArray optJSONObjectWithInt:i];
      self->name_ = [((FQJSONObject *) nil_chk(mObject)) optStringWithNSString:@"name"];
      self->userId_ = [mObject optIntWithNSString:@"user_id"];
      self->headIcon_ = [mObject optStringWithNSString:@"head_icon"];
    }
  }
  else {
    
#line 26
    self->name_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getName];
    self->userId_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId];
    self->headIcon_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getHeadPicPath];
  }
}


#line 34
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)mObject {
  
#line 38
  self->name_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getName];
  self->userId_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId];
  self->headIcon_ = [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getHeadPicPath];
}


#line 43
- (int)getUserId {
  
#line 44
  return userId_;
}


#line 47
- (void)setUserIdWithInt:(int)userId {
  
#line 48
  self->userId_ = userId;
}


#line 51
- (NSString *)getName {
  
#line 52
  return name_;
}


#line 55
- (void)setNameWithNSString:(NSString *)name {
  
#line 56
  self->name_ = name;
}


#line 59
- (NSString *)getHeadIcon {
  
#line 60
  return headIcon_;
}


#line 63
- (void)setHeadIconWithNSString:(NSString *)headIcon {
  
#line 64
  self->headIcon_ = headIcon;
}

- (id)init {
  return [super init];
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityTimerMember *)other {
  [super copyAllFieldsTo:other];
  other->headIcon_ = headIcon_;
  other->name_ = name_;
  other->userId_ = userId_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "setAtttributeByjsonWithFQJSONArray:", "setAtttributeByjson", "V", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "getUserId", NULL, "I", 0x1, NULL },
    { "setUserIdWithInt:", "setUserId", "V", 0x1, NULL },
    { "getName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setNameWithNSString:", "setName", "V", 0x1, NULL },
    { "getHeadIcon", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setHeadIconWithNSString:", "setHeadIcon", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "userId_", NULL, 0x1, "I", NULL,  },
    { "name_", NULL, 0x1, "Ljava.lang.String;", NULL,  },
    { "headIcon_", NULL, 0x1, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityTimerMember = { "TimerMember", "com.fq.halcyon.entity", NULL, 0x1, 9, methods, 3, fields, 0, NULL};
  return &_ComFqHalcyonEntityTimerMember;
}

@end
