//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/uilogic/UILoginLogic.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonUilogicUILoginLogic_H_
#define _ComFqHalcyonUilogicUILoginLogic_H_

@protocol ComFqHalcyonUilogicUILoginLogic_UILogicCallback;

#import "JreEmulation.h"
#include "AlarmClockLogic.h"
#include "ICallback.h"
#include "LoginLogic.h"
#include "ResetDoctorInfoLogic.h"

@interface ComFqHalcyonUilogicUILoginLogic : NSObject {
 @public
  ComFqHalcyonLogicLoginLogic *mLoginLogic_;
  id<ComFqHalcyonUilogicUILoginLogic_UILogicCallback> mCallback_;
  NSString *mPhoneNumber_;
  NSString *mPwd_;
}

- (id)initWithComFqHalcyonUilogicUILoginLogic_UILogicCallback:(id<ComFqHalcyonUilogicUILoginLogic_UILogicCallback>)callback;

- (void)loginWithBoolean:(BOOL)isHaveNet
            withNSString:(NSString *)phoneNumber
            withNSString:(NSString *)pwd
            withNSString:(NSString *)clientVersion
            withNSString:(NSString *)clientType;

- (void)checkUser;

- (void)initInvient OBJC_METHOD_FAMILY_NONE;

- (void)initUserHead OBJC_METHOD_FAMILY_NONE;

- (void)copyAllFieldsTo:(ComFqHalcyonUilogicUILoginLogic *)other;

@end

FOUNDATION_EXPORT BOOL ComFqHalcyonUilogicUILoginLogic_initialized;
J2OBJC_STATIC_INIT(ComFqHalcyonUilogicUILoginLogic)

J2OBJC_FIELD_SETTER(ComFqHalcyonUilogicUILoginLogic, mLoginLogic_, ComFqHalcyonLogicLoginLogic *)
J2OBJC_FIELD_SETTER(ComFqHalcyonUilogicUILoginLogic, mCallback_, id<ComFqHalcyonUilogicUILoginLogic_UILogicCallback>)
J2OBJC_FIELD_SETTER(ComFqHalcyonUilogicUILoginLogic, mPhoneNumber_, NSString *)
J2OBJC_FIELD_SETTER(ComFqHalcyonUilogicUILoginLogic, mPwd_, NSString *)

FOUNDATION_EXPORT NSString *ComFqHalcyonUilogicUILoginLogic_TAG_;
J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonUilogicUILoginLogic, TAG_, NSString *)

@protocol ComFqHalcyonUilogicUILoginLogic_UILogicCallback < NSObject, JavaObject >

- (void)logicBackWithInt:(int)type
                 withInt:(int)code
            withNSString:(NSString *)msg;

- (void)onAlarmCallback;

@end

__attribute__((always_inline)) inline void ComFqHalcyonUilogicUILoginLogic_UILogicCallback_init() {}

@interface ComFqHalcyonUilogicUILoginLogic_$1 : ComFqHalcyonLogicLoginLogic {
 @public
  ComFqHalcyonUilogicUILoginLogic *this$0_;
}

- (void)returnErrorWithInt:(int)code
              withNSString:(NSString *)msg;

- (void)loginSucess;

- (id)initWithComFqHalcyonUilogicUILoginLogic:(ComFqHalcyonUilogicUILoginLogic *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonUilogicUILoginLogic_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonUilogicUILoginLogic_$1, this$0_, ComFqHalcyonUilogicUILoginLogic *)

@interface ComFqHalcyonUilogicUILoginLogic_$1_$1 : NSObject < ComFqHalcyonLogic2AlarmClockLogic_AlarmClockLogicCallBack > {
 @public
  ComFqHalcyonUilogicUILoginLogic_$1 *this$0_;
}

- (void)onResultCallBackWithInt:(int)code;

- (void)onErrorCallBackWithInt:(int)code
                  withNSString:(NSString *)msg;

- (id)initWithComFqHalcyonUilogicUILoginLogic_$1:(ComFqHalcyonUilogicUILoginLogic_$1 *)outer$;

@end

__attribute__((always_inline)) inline void ComFqHalcyonUilogicUILoginLogic_$1_$1_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonUilogicUILoginLogic_$1_$1, this$0_, ComFqHalcyonUilogicUILoginLogic_$1 *)

@interface ComFqHalcyonUilogicUILoginLogic_$2 : NSObject < ComFqHalcyonLogic2ResetDoctorInfoLogic_InvientCallback > {
}

- (void)doInvientBackWithNSString:(NSString *)invient;

- (id)init;

@end

__attribute__((always_inline)) inline void ComFqHalcyonUilogicUILoginLogic_$2_init() {}

@interface ComFqHalcyonUilogicUILoginLogic_$3 : NSObject < ComFqLibCallbackICallback > {
}

- (void)doCallbackWithId:(id)obj;

- (id)init;

@end

__attribute__((always_inline)) inline void ComFqHalcyonUilogicUILoginLogic_$3_init() {}

#endif // _ComFqHalcyonUilogicUILoginLogic_H_
