//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/UploadFeedBackLogic.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/logic2/UploadFeedBackLogic.java"

#include "ApiSystem.h"
#include "Constants.h"
#include "FQHttpParams.h"
#include "HttpRequestPotocol.h"
#include "JSONObject.h"
#include "JsonHelper.h"
#include "UploadFeedBackLogic.h"
#include "UriConstants.h"
#include "User.h"
#include "java/lang/Integer.h"
#include "java/lang/Throwable.h"
#include "java/util/HashMap.h"


#line 16
@implementation ComFqHalcyonLogic2UploadFeedBackLogic


#line 47
- (id)initWithComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface:(id<ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface>)mIn
                                                                    withNSString:(NSString *)feedInfo {
  if (self = [super init]) {
    mHandle_ =
#line 45
    [[ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicHandle alloc] initWithComFqHalcyonLogic2UploadFeedBackLogic:self];
    
#line 48
    mInterface_ = mIn;
    
#line 49
    JavaUtilHashMap *map = [[JavaUtilHashMap alloc] init];
    
#line 50
    (void) [map putWithId:@"user_id" withId:[JavaLangInteger valueOfWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getUserId]]];
    
#line 51
    (void) [map putWithId:@"feed_info" withId:feedInfo];
    
#line 52
    FQJSONObject *json = [ComFqLibJsonHelper createJsonWithJavaUtilMap:map];
    
#line 53
    (void) [((ComFqHalcyonApiApiSystem *) nil_chk([ComFqHalcyonApiApiSystem getInstance])) requireWithNSString:[NSString stringWithFormat:@"%@/users/add_feed.do", ComFqLibToolsUriConstants_Conn_get_URL_PUB_()] withComFqHttpAsyncFQHttpParams:[[ComFqHttpAsyncFQHttpParams alloc] initWithFQJSONObject:json] withComFqHalcyonApiApiSystem_API_TYPEEnum:ComFqHalcyonApiApiSystem_API_TYPEEnum_get_DIRECT() withHalcyonHttpResponseHandle:mHandle_];
  }
  return self;
}

- (void)copyAllFieldsTo:(ComFqHalcyonLogic2UploadFeedBackLogic *)other {
  [super copyAllFieldsTo:other];
  other->mHandle_ = mHandle_;
  other->mInterface_ = mInterface_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface:withNSString:", "UploadFeedBackLogic", NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mInterface_", NULL, 0x2, "Lcom.fq.halcyon.logic2.UploadFeedBackLogic$UploadFeedBackLogicInterface;", NULL,  },
    { "mHandle_", NULL, 0x2, "Lcom.fq.halcyon.logic2.UploadFeedBackLogic$UploadFeedBackLogicHandle;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2UploadFeedBackLogic = { "UploadFeedBackLogic", "com.fq.halcyon.logic2", NULL, 0x1, 1, methods, 2, fields, 0, NULL};
  return &_ComFqHalcyonLogic2UploadFeedBackLogic;
}

@end

@interface ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface : NSObject
@end

@implementation ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onDaraReturnWithInt:withNSString:", "onDaraReturn", "V", 0x401, NULL },
    { "onErrorReturnWithInt:withJavaLangThrowable:", "onErrorReturn", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface = { "UploadFeedBackLogicInterface", "com.fq.halcyon.logic2", "UploadFeedBackLogic", 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface;
}

@end


#line 26
@implementation ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicHandle


#line 29
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 30
  [((id<ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface>) nil_chk(this$0_->mInterface_)) onErrorReturnWithInt:code withJavaLangThrowable:e];
}


#line 34
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  if (responseCode == 0) {
    [((id<ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface>) nil_chk(this$0_->mInterface_)) onDaraReturnWithInt:responseCode withNSString:msg];
  }
  else {
    
#line 39
    [((id<ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicInterface>) nil_chk(this$0_->mInterface_)) onErrorReturnWithInt:responseCode withJavaLangThrowable:[[JavaLangThrowable alloc] init]];
  }
}

- (id)initWithComFqHalcyonLogic2UploadFeedBackLogic:(ComFqHalcyonLogic2UploadFeedBackLogic *)outer$ {
  this$0_ = outer$;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqHalcyonLogic2UploadFeedBackLogic:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.halcyon.logic2.UploadFeedBackLogic;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicHandle = { "UploadFeedBackLogicHandle", "com.fq.halcyon.logic2", "UploadFeedBackLogic", 0x2, 3, methods, 1, fields, 0, NULL};
  return &_ComFqHalcyonLogic2UploadFeedBackLogic_UploadFeedBackLogicHandle;
}

@end
