//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/UserAction.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/UserAction.java"

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "JSONException.h"
#include "JSONObject.h"
#include "TimeFormatUtils.h"
#include "UserAction.h"


#line 7
@implementation ComFqHalcyonEntityUserAction


#line 32
- (id)init {
  if (self = [super init]) {
    actions_ = [IOSObjectArray arrayWithObjects:(id[]){
#line 24
      @"\u6ce8\u518c", @"\u4e0a\u4f20\u75c5\u5386", @"\u6dfb\u52a0\u75c5\u4eba", @"\u6dfb\u52a0\u533b\u751f", @"\u8bbe\u7f6e\u63d0\u9192", @"\u63d0\u9192\u7559\u8a00", @"\u770b\u8fc7\u60a3\u8005" } count:7 type:[IOSClass classWithClass:[NSString class]]];
    }
    return self;
  }


#line 34
- (id)initWithLong:(long long int)date
           withInt:(int)action
      withNSString:(NSString *)des {
  if (self = [super init]) {
    actions_ = [IOSObjectArray arrayWithObjects:(id[]){
#line 24
      @"\u6ce8\u518c", @"\u4e0a\u4f20\u75c5\u5386", @"\u6dfb\u52a0\u75c5\u4eba", @"\u6dfb\u52a0\u533b\u751f", @"\u8bbe\u7f6e\u63d0\u9192", @"\u63d0\u9192\u7559\u8a00", @"\u770b\u8fc7\u60a3\u8005" } count:7 type:[IOSClass classWithClass:[NSString class]]];
      
#line 35
      self->date_ = date;
      
#line 36
      self->action_ = action;
      
#line 37
      self->des_ = des;
    }
    return self;
  }


#line 40
- (long long int)getDate {
  
#line 41
  return date_;
}


#line 43
- (void)setDateWithLong:(long long int)date {
  
#line 44
  self->date_ = date;
}


#line 46
- (NSString *)getDateStr {
  
#line 47
  return [ComFqLibToolsTimeFormatUtils getTimeByFormatWithLong:date_ withNSString:@"MM/dd"];
}

- (NSString *)getActionStr {
  
#line 53
  return IOSObjectArray_Get(nil_chk(actions_), action_);
}


#line 55
- (int)getAction {
  
#line 56
  return action_;
}


#line 58
- (void)setActionWithInt:(int)action {
  
#line 59
  self->action_ = action;
}


#line 61
- (NSString *)getDes {
  
#line 62
  return des_;
}


#line 64
- (void)setDesWithNSString:(NSString *)des {
  
#line 65
  self->des_ = des;
}


#line 68
- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json {
  
#line 69
  self->date_ = [((FQJSONObject *) nil_chk(json)) optLongWithNSString:@"date"];
  self->action_ = [json optIntWithNSString:@"action"];
  self->des_ = [json optStringWithNSString:@"des"];
}


#line 74
- (FQJSONObject *)getJson {
  
#line 75
  FQJSONObject *obj = [[FQJSONObject alloc] init];
  @try {
    (void) [obj putWithNSString:@"date" withLong:date_];
    (void) [obj putWithNSString:@"action" withInt:action_];
    (void) [obj putWithNSString:@"des" withId:des_];
    return obj;
  }
  @catch (
#line 81
  FQJSONException *e) {
    [((FQJSONException *) nil_chk(e)) printStackTrace];
    return nil;
  }
}

- (void)copyAllFieldsTo:(ComFqHalcyonEntityUserAction *)other {
  [super copyAllFieldsTo:other];
  other->action_ = action_;
  other->actions_ = actions_;
  other->date_ = date_;
  other->des_ = des_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "init", "UserAction", NULL, 0x1, NULL },
    { "initWithLong:withInt:withNSString:", "UserAction", NULL, 0x1, NULL },
    { "getDate", NULL, "J", 0x1, NULL },
    { "setDateWithLong:", "setDate", "V", 0x1, NULL },
    { "getDateStr", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getActionStr", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getAction", NULL, "I", 0x1, NULL },
    { "setActionWithInt:", "setAction", "V", 0x1, NULL },
    { "getDes", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setDesWithNSString:", "setDes", "V", 0x1, NULL },
    { "setAtttributeByjsonWithFQJSONObject:", "setAtttributeByjson", "V", 0x1, NULL },
    { "getJson", NULL, "Lcom.fq.lib.json.JSONObject;", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "ACTION_REGIST_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_REGIST },
    { "ACTION_UP_RECORD_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_UP_RECORD },
    { "ACTION_ADD_PATIENT_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_ADD_PATIENT },
    { "ACTION_ADD_DEOCTOR_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_ADD_DEOCTOR },
    { "ACTION_SET_TIMER_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_SET_TIMER },
    { "ACTION_ADD_REMARK_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_ADD_REMARK },
    { "ACTION_VIEW_PATIENT_", NULL, 0x19, "I", NULL, .constantValue.asInt = ComFqHalcyonEntityUserAction_ACTION_VIEW_PATIENT },
    { "actions_", NULL, 0x2, "[Ljava.lang.String;", NULL,  },
    { "date_", NULL, 0x2, "J", NULL,  },
    { "action_", NULL, 0x2, "I", NULL,  },
    { "des_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqHalcyonEntityUserAction = { "UserAction", "com.fq.halcyon.entity", NULL, 0x1, 12, methods, 11, fields, 0, NULL};
  return &_ComFqHalcyonEntityUserAction;
}

@end
