//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/halcyon/entity/UserAction.java
//
//  Created by liaomin on 15-5-4.
//

#ifndef _ComFqHalcyonEntityUserAction_H_
#define _ComFqHalcyonEntityUserAction_H_

@class FQJSONObject;
@class IOSObjectArray;

#import "JreEmulation.h"

#define ComFqHalcyonEntityUserAction_ACTION_ADD_DEOCTOR 3
#define ComFqHalcyonEntityUserAction_ACTION_ADD_PATIENT 2
#define ComFqHalcyonEntityUserAction_ACTION_ADD_REMARK 5
#define ComFqHalcyonEntityUserAction_ACTION_REGIST 0
#define ComFqHalcyonEntityUserAction_ACTION_SET_TIMER 4
#define ComFqHalcyonEntityUserAction_ACTION_UP_RECORD 1
#define ComFqHalcyonEntityUserAction_ACTION_VIEW_PATIENT 6

@interface ComFqHalcyonEntityUserAction : NSObject {
 @public
  IOSObjectArray *actions_;
  long long int date_;
  int action_;
  NSString *des_;
}

- (id)init;

- (id)initWithLong:(long long int)date
           withInt:(int)action
      withNSString:(NSString *)des;

- (long long int)getDate;

- (void)setDateWithLong:(long long int)date;

- (NSString *)getDateStr;

- (NSString *)getActionStr;

- (int)getAction;

- (void)setActionWithInt:(int)action;

- (NSString *)getDes;

- (void)setDesWithNSString:(NSString *)des;

- (void)setAtttributeByjsonWithFQJSONObject:(FQJSONObject *)json;

- (FQJSONObject *)getJson;

- (void)copyAllFieldsTo:(ComFqHalcyonEntityUserAction *)other;

@end

__attribute__((always_inline)) inline void ComFqHalcyonEntityUserAction_init() {}

J2OBJC_FIELD_SETTER(ComFqHalcyonEntityUserAction, actions_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComFqHalcyonEntityUserAction, des_, NSString *)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_REGIST, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_UP_RECORD, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_ADD_PATIENT, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_ADD_DEOCTOR, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_SET_TIMER, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_ADD_REMARK, int)

J2OBJC_STATIC_FIELD_GETTER(ComFqHalcyonEntityUserAction, ACTION_VIEW_PATIENT, int)

#endif // _ComFqHalcyonEntityUserAction_H_
