//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/tools/UserProfileManager.java
//
//  Created by liaomin on 15-5-4.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/lib/tools/UserProfileManager.java"

#include "Constants.h"
#include "FQLog.h"
#include "FileSystem.h"
#include "JSONObject.h"
#include "ResetDoctorInfoLogic.h"
#include "UploadImageHelper.h"
#include "User.h"
#include "UserProfileManager.h"
#include "java/io/File.h"
#include "java/lang/Integer.h"
#include "java/lang/System.h"
#include "java/lang/Throwable.h"


#line 13
@implementation ComFqLibToolsUserProfileManager

ComFqLibToolsUserProfileManager * ComFqLibToolsUserProfileManager_mInstance_;


#line 20
+ (ComFqLibToolsUserProfileManager *)instance {
  
#line 21
  if (ComFqLibToolsUserProfileManager_mInstance_ == nil) {
    ComFqLibToolsUserProfileManager_mInstance_ = [[ComFqLibToolsUserProfileManager alloc] init];
    ComFqLibToolsUserProfileManager_mInstance_->mUser_ = [ComFqLibToolsConstants getUser];
    ComFqLibToolsUserProfileManager_mInstance_->resetDoctorInfoLogic_ = [[ComFqHalcyonLogic2ResetDoctorInfoLogic alloc] init];
  }
  return ComFqLibToolsUserProfileManager_mInstance_;
}


#line 33
- (ComFqHalcyonEntityUser *)getUser {
  
#line 34
  return mUser_;
}


#line 40
- (void)clear {
  
#line 41
  ((ComFqLibToolsUserProfileManager *) nil_chk(ComFqLibToolsUserProfileManager_mInstance_))->mUser_ = nil;
  ComFqLibToolsUserProfileManager_mInstance_ = nil;
}


#line 50
- (JavaIoFile *)getLocalTempFileUri {
  
#line 51
  localTempImageFileName_ = [NSString stringWithFormat:@"head%lld", [JavaLangSystem currentTimeMillis]];
  JavaIoFile *filePath = [[JavaIoFile alloc] initWithNSString:[((ComFqHalcyonExtendFilesystemFileSystem *) nil_chk([ComFqHalcyonExtendFilesystemFileSystem getInstance])) getFriendPath]];
  if (![filePath exists])
#line 54
  [filePath mkdirs];
  return [[JavaIoFile alloc] initWithJavaIoFile:filePath withNSString:localTempImageFileName_];
}

- (NSString *)getlocaltempimageFileName {
  
#line 62
  return localTempImageFileName_;
}

- (NSString *)getlocaltempimageFilegetAbsolutePath {
  
#line 68
  JavaIoFile *f = [[JavaIoFile alloc] initWithNSString:[NSString stringWithFormat:@"%@%@", [((ComFqHalcyonExtendFilesystemFileSystem *) nil_chk([ComFqHalcyonExtendFilesystemFileSystem getInstance])) getFriendPath],
#line 69
  localTempImageFileName_]];
  return [f getAbsolutePath];
}


#line 80
- (void)getInvientWithComFqHalcyonEntityUser:(ComFqHalcyonEntityUser *)mUser
withComFqLibToolsUserProfileManager_OnResultCallBack:(id<ComFqLibToolsUserProfileManager_OnResultCallBack>)callBack {
  
#line 81
  if ([@"" isEqual:[((ComFqHalcyonEntityUser *) nil_chk(mUser)) getInvition]]) {
    [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) requestInvientWithComFqHalcyonLogic2ResetDoctorInfoLogic_InvientCallback:[[ComFqLibToolsUserProfileManager_$1 alloc] initWithComFqLibToolsUserProfileManager_OnResultCallBack:callBack withComFqHalcyonEntityUser:mUser]];
  }
  else {
    
#line 94
    [((id<ComFqLibToolsUserProfileManager_OnResultCallBack>) nil_chk(callBack)) onResultWithNSString:[mUser getInvition]];
  }
}


#line 105
- (BOOL)isFirstLogin {
  
#line 106
  return [@"" isEqual:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getName]] ||
#line 107
  ([((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getRole_type] == ComFqLibToolsConstants_ROLE_DOCTOR && [@"" isEqual:
#line 108
  [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getDepartment]]) ||
#line 109
  ([((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getRole_type] == ComFqLibToolsConstants_ROLE_DOCTOR && [@"" isEqual:
#line 110
  [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getHospital]]) ||
#line 111
  ([((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getRole_type] == ComFqLibToolsConstants_ROLE_DOCTOR && [@"" isEqual:
#line 112
  [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getTitleStr]]) ||
#line 113
  [@"" isEqual:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getGenderStr]];
}


#line 123
- (NSString *)getSelectZhiChengWithId:(id)obj
                          withBoolean:(BOOL)mIsDoctor {
  
#line 124
  int index = [((JavaLangInteger *) nil_chk((JavaLangInteger *) check_class_cast(obj, [JavaLangInteger class]))) intValue];
  if (mIsDoctor) {
    if (index != [((ComFqHalcyonEntityUser *) nil_chk(mUser_)) getTitle]) {
      [mUser_ setTitleWithInt:index];
      [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyTitleWithInt:[mUser_ getTitle]];
      return [mUser_ getTitleStr];
    }
  }
  else {
    
#line 132
    if (index != [((ComFqHalcyonEntityUser *) nil_chk(mUser_)) getEducation]) {
      [mUser_ setEducationWithInt:index];
      [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyEducationWithInt:[mUser_ getEducation]];
      return [mUser_ getEducationStr];
    }
  }
  return nil;
}


#line 144
- (void)upLoadHeadWithComFqLibToolsUserProfileManager_OnUploadCallBack:(id<ComFqLibToolsUserProfileManager_OnUploadCallBack>)callBack {
  
#line 145
  ComFqHalcyonExtendFilesystemFileSystem *fileSys = [ComFqHalcyonExtendFilesystemFileSystem getInstance];
  [((ComFqLibUploadImageHelper *) [[ComFqLibUploadImageHelper alloc] init]) upLoadImgWithNSString:[((ComFqHalcyonExtendFilesystemFileSystem *) nil_chk(fileSys)) getUserHeadPath] withHalcyonHttpResponseHandle:
#line 147
  [[ComFqLibToolsUserProfileManager_$2 alloc] initWithComFqLibToolsUserProfileManager:self withComFqLibToolsUserProfileManager_OnUploadCallBack:callBack withComFqHalcyonExtendFilesystemFileSystem:fileSys]];
}


#line 182
- (void)reqModyName {
  
#line 183
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyNameWithNSString:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getName]];
}


#line 189
- (void)reqModyHospWithInt:(int)hosId
              withNSString:(NSString *)hosName {
  
#line 190
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyHospWithInt:0 withInt:hosId withNSString:hosName];
}

- (void)reqModyDeptWithInt:(int)deptId
                   withInt:(int)secId
              withNSString:(NSString *)name {
  
#line 197
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyDeptWithInt:deptId withInt:secId withNSString:name];
}


#line 202
- (void)reqModyGender {
  
#line 203
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyGenderWithInt:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getGender]];
}


#line 209
- (void)reqModyDes {
  
#line 210
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyDesWithNSString:[((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) getDescription]];
}


#line 216
- (void)reqModyUniversity {
  
#line 217
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyUniversityWithNSString:[((ComFqHalcyonEntityUser *) nil_chk(mUser_)) getUniversity]];
}


#line 224
- (void)reqModyEntranceTimeWithNSString:(NSString *)time {
  
#line 225
  [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) setEntranceTimeWithNSString:time];
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(resetDoctorInfoLogic_)) reqModyEntranceTimeWithNSString:time];
}

- (id)init {
  if (self = [super init]) {
    localTempImageFileName_ =
#line 18
    @"";
  }
  return self;
}

- (void)copyAllFieldsTo:(ComFqLibToolsUserProfileManager *)other {
  [super copyAllFieldsTo:other];
  other->localTempImageFileName_ = localTempImageFileName_;
  other->mUser_ = mUser_;
  other->resetDoctorInfoLogic_ = resetDoctorInfoLogic_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "instance", NULL, "Lcom.fq.lib.tools.UserProfileManager;", 0x9, NULL },
    { "getUser", NULL, "Lcom.fq.halcyon.entity.User;", 0x1, NULL },
    { "clear", NULL, "V", 0x1, NULL },
    { "getLocalTempFileUri", NULL, "Ljava.io.File;", 0x1, NULL },
    { "getlocaltempimageFileName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getlocaltempimageFilegetAbsolutePath", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getInvientWithComFqHalcyonEntityUser:withComFqLibToolsUserProfileManager_OnResultCallBack:", "getInvient", "V", 0x1, NULL },
    { "isFirstLogin", NULL, "Z", 0x1, NULL },
    { "getSelectZhiChengWithId:withBoolean:", "getSelectZhiCheng", "Ljava.lang.String;", 0x1, NULL },
    { "upLoadHeadWithComFqLibToolsUserProfileManager_OnUploadCallBack:", "upLoadHead", "V", 0x1, NULL },
    { "reqModyName", NULL, "V", 0x1, NULL },
    { "reqModyHospWithInt:withNSString:", "reqModyHosp", "V", 0x1, NULL },
    { "reqModyDeptWithInt:withInt:withNSString:", "reqModyDept", "V", 0x1, NULL },
    { "reqModyGender", NULL, "V", 0x1, NULL },
    { "reqModyDes", NULL, "V", 0x1, NULL },
    { "reqModyUniversity", NULL, "V", 0x1, NULL },
    { "reqModyEntranceTimeWithNSString:", "reqModyEntranceTime", "V", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "mInstance_", NULL, 0xa, "Lcom.fq.lib.tools.UserProfileManager;", &ComFqLibToolsUserProfileManager_mInstance_,  },
    { "resetDoctorInfoLogic_", NULL, 0x2, "Lcom.fq.halcyon.logic2.ResetDoctorInfoLogic;", NULL,  },
    { "mUser_", NULL, 0x2, "Lcom.fq.halcyon.entity.User;", NULL,  },
    { "localTempImageFileName_", NULL, 0x2, "Ljava.lang.String;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqLibToolsUserProfileManager = { "UserProfileManager", "com.fq.lib.tools", NULL, 0x1, 18, methods, 4, fields, 0, NULL};
  return &_ComFqLibToolsUserProfileManager;
}

@end

@interface ComFqLibToolsUserProfileManager_OnResultCallBack : NSObject
@end

@implementation ComFqLibToolsUserProfileManager_OnResultCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onResultWithNSString:", "onResult", "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqLibToolsUserProfileManager_OnResultCallBack = { "OnResultCallBack", "com.fq.lib.tools", "UserProfileManager", 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComFqLibToolsUserProfileManager_OnResultCallBack;
}

@end

@interface ComFqLibToolsUserProfileManager_OnUploadCallBack : NSObject
@end

@implementation ComFqLibToolsUserProfileManager_OnUploadCallBack

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onError", NULL, "V", 0x401, NULL },
    { "onsuccess", NULL, "V", 0x401, NULL },
  };
  static J2ObjcClassInfo _ComFqLibToolsUserProfileManager_OnUploadCallBack = { "OnUploadCallBack", "com.fq.lib.tools", "UserProfileManager", 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_ComFqLibToolsUserProfileManager_OnUploadCallBack;
}

@end

@implementation ComFqLibToolsUserProfileManager_$1


#line 84
- (void)doInvientBackWithNSString:(NSString *)invient {
  
#line 85
  if ([@"" isEqual:invient]) {
    [((id<ComFqLibToolsUserProfileManager_OnResultCallBack>) nil_chk(val$callBack_)) onResultWithNSString:@"\u83b7\u53d6\u4e2d"];
  }
  else {
    
#line 88
    [((id<ComFqLibToolsUserProfileManager_OnResultCallBack>) nil_chk(val$callBack_)) onResultWithNSString:invient];
    [((ComFqHalcyonEntityUser *) nil_chk(val$mUser_)) setInvitionWithNSString:invient];
  }
}

- (id)initWithComFqLibToolsUserProfileManager_OnResultCallBack:(id<ComFqLibToolsUserProfileManager_OnResultCallBack>)capture$0
                                    withComFqHalcyonEntityUser:(ComFqHalcyonEntityUser *)capture$1 {
  val$callBack_ = capture$0;
  val$mUser_ = capture$1;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "doInvientBackWithNSString:", "doInvientBack", "V", 0x1, NULL },
    { "initWithComFqLibToolsUserProfileManager_OnResultCallBack:withComFqHalcyonEntityUser:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$callBack_", NULL, 0x1012, "Lcom.fq.lib.tools.UserProfileManager$OnResultCallBack;", NULL,  },
    { "val$mUser_", NULL, 0x1012, "Lcom.fq.halcyon.entity.User;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqLibToolsUserProfileManager_$1 = { "$1", "com.fq.lib.tools", "UserProfileManager", 0x8000, 2, methods, 2, fields, 0, NULL};
  return &_ComFqLibToolsUserProfileManager_$1;
}

@end

@implementation ComFqLibToolsUserProfileManager_$2


#line 149
- (void)onErrorWithInt:(int)code
 withJavaLangThrowable:(JavaLangThrowable *)e {
  
#line 150
  [ComFqLibToolsFQLog iWithNSString:@"sendHead" withNSString:[NSString stringWithFormat:@"~~send head falid:code:%d msg:%@", code,
#line 151
  e]];
  [((id<ComFqLibToolsUserProfileManager_OnUploadCallBack>) nil_chk(val$callBack_)) onError];
}


#line 156
- (void)handleWithInt:(int)responseCode
         withNSString:(NSString *)msg
              withInt:(int)type
               withId:(id)results {
  
#line 158
  FQJSONObject *obj = (FQJSONObject *) check_class_cast(results, [FQJSONObject class]);
  [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) setHeadPicPathWithNSString:
#line 160
  [((ComFqHalcyonExtendFilesystemFileSystem *) nil_chk(val$fileSys_)) getUserHeadPath]];
  int id_ = [((FQJSONObject *) nil_chk(obj)) optIntWithNSString:@"image_id"];
  [((ComFqHalcyonEntityUser *) nil_chk([ComFqLibToolsConstants getUser])) setHeadPicImageIdWithInt:id_];
  [((ComFqHalcyonLogic2ResetDoctorInfoLogic *) nil_chk(this$0_->resetDoctorInfoLogic_)) reqModyHeadWithInt:id_];
  [((id<ComFqLibToolsUserProfileManager_OnUploadCallBack>) nil_chk(val$callBack_)) onsuccess];
}

- (id)initWithComFqLibToolsUserProfileManager:(ComFqLibToolsUserProfileManager *)outer$
withComFqLibToolsUserProfileManager_OnUploadCallBack:(id<ComFqLibToolsUserProfileManager_OnUploadCallBack>)capture$0
   withComFqHalcyonExtendFilesystemFileSystem:(ComFqHalcyonExtendFilesystemFileSystem *)capture$1 {
  this$0_ = outer$;
  val$callBack_ = capture$0;
  val$fileSys_ = capture$1;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "onErrorWithInt:withJavaLangThrowable:", "onError", "V", 0x1, NULL },
    { "handleWithInt:withNSString:withInt:withId:", "handle", "V", 0x1, NULL },
    { "initWithComFqLibToolsUserProfileManager:withComFqLibToolsUserProfileManager_OnUploadCallBack:withComFqHalcyonExtendFilesystemFileSystem:", "init", NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "Lcom.fq.lib.tools.UserProfileManager;", NULL,  },
    { "val$callBack_", NULL, 0x1012, "Lcom.fq.lib.tools.UserProfileManager$OnUploadCallBack;", NULL,  },
    { "val$fileSys_", NULL, 0x1012, "Lcom.fq.halcyon.extend.filesystem.FileSystem;", NULL,  },
  };
  static J2ObjcClassInfo _ComFqLibToolsUserProfileManager_$2 = { "$2", "com.fq.lib.tools", "UserProfileManager", 0x8000, 3, methods, 3, fields, 0, NULL};
  return &_ComFqLibToolsUserProfileManager_$2;
}

@end
